### ISSUE TITLE
Expanding filesystem currently broken

### ISSUE THREAD

**Issue by ghollingworth** [raspberrypi/bookworm-feedback#1]
Expanding the ext4 filesystem to fill the SD card on first boot is currently broken.

**Comment by BlackNet** [comment]
Correct. I was able to manually extend that with raspi-config. I tested with a cm4 on an oratek tofu carrier board with m2 1TB mounted as root. Same issues.

**Comment by paulober** [comment]
Can confirm. Had the same issue but `raspi-config` was able to extend it manually.

**Comment by lurch** [comment]
@XECDesign This has been fixed now, right?

**Comment by XECDesign** [comment]
yes

**Comment by martignoni** [comment]
Confirming, resizing works out of the box with image 2023-09-22.

**Comment by andrum993** [comment]
Adding my +1 - resize works on Pi 4B with both USB boot and root (SATA SSD) and internal SD card boot and root.

**Comment by munderwoods** [comment]
I'm actually having this issue on the version I downloaded from here:
https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2023-12-11/2023-12-11-raspios-bookworm-armhf-lite.img.xz

Am I doing something dumb?

**Comment by lurch** [comment]
@munderwoods I've just tested this myself, writing the image you linked above onto a 16GB microSD card, and booting it up on a Raspberry Pi Zero 2 W.
On the first bootup, it generates the SSH keys and resizes the root filesystem. It then automatically reboots and on the second bootup it asks me for keyboard and username settings. When I then login and run `lsblk` I can see that `mmcblk0p2` (the root filesystem) has been resized to 14.3GB.

Can you please give more details on how this isn't working for you / what behaviour you're seeing instead?

**Comment by munderwoods** [comment]
> @munderwoods I've just tested this myself, writing the image you linked above onto a 16GB microSD card, and booting it up on a Raspberry Pi Zero 2 W. On the first bootup, it generates the SSH keys and resizes the root filesystem. It then automatically reboots and on the second bootup it asks me for keyboard and username settings. When I then login and run `lsblk` I can see that `mmcblk0p2` (the root filesystem) has been resized to 14.3GB.
> 
> Can you please give more details on how this isn't working for you / what behaviour you're seeing instead?

Super sorry, I totally wasted your time. It was entirely my mistake! I was doing some pre-configuration on the image and didn't realize (for far too long) that I was over-writing the boot/config.txt instead of appending to it. Really dumb.

**Comment by lurch** [comment]
Easily done, when the difference is `>` vs. `>>` :slightly_smiling_face:   Glad to hear that things are working now.
