### ISSUE TITLE
NFS Mount different from Bullseye?

### ISSUE THREAD

**Issue by GeekyTim** [raspberrypi/bookworm-feedback#10]
I have a tool that I use to configure a bunch of small specific tools on all my Pi's, including some NFS mounts to my NAS. Currently, the /etc/fstab entry is:

prometheus:PiShared /home/geekytim/PiShared nfs nfsvers=4,rw,soft 0 0

But this does not work within bookworm.

**Comment by GeekyTim** [comment]
This might be something specific to my NAS; the firmware was recently updated. I just went back to some of my other Pi servers, and they are having problems, but reporting different issues.

**Comment by GeekyTim** [comment]
Allowing ALL local IP addresses allows me to mount a drive from the NAS on my Pi5/Bookworm. Using the Pi 5's hostname does not work - although it does work on Bullseye images on earlier Pis (2/3/4). Hard to tell if this is a bookworm issue or a NAS issue at the moment, so I need to look into this further before we consider this a problem with this latest Pi OS. 

I must admit I have disabled SMB on the NAS, which many would take as their default sharing protocol, but since 95% of my home servers are Pi's and the other two run Linux, I want to stay away from the dark side.

**Comment by gitbls** [comment]
I'm not seeing any issues mounting shares on Bullseye Pi or x64 servers from my Bookworm client.
