### ISSUE TITLE
Pi5 16K PageSize Kernel Incompatible Software

### ISSUE THREAD

**Issue by theofficialgman** [raspberrypi/bookworm-feedback#107]
This issue will be a public tracker for 16K pagesize incompatible software. I made a similar post in the bookworm beta forum thread but that is still not public.

Feel free to add your own incompatible software as a comment and I will add it to this post.

Much of this list is thanks to Asahi linux wiki https://github.com/AsahiLinux/docs/wiki/Broken-Software

Broken software:
- f2fs
- FEX
- hardened_malloc
- jemalloc
  - Geekbench 6 (< 6.2.2)
  - Minecraft Java (on versions and launchers without the <3.3.2 lwjgl native jemalloc patch)
  - rust
- fd
- Wine ARM64
- Wine x86_64 through Box64
- Box86
- Zig
- All Chromium based applications (pre-102)
  - qt5-webengine
  - qt6-webengine (QtPdf)
- libvirt/QEMU/KVM (fixed in versions newer than bookworm has)
- All Android applications (only 4k header compatible, https://reviews.llvm.org/D55029)
  - Minecraft Bedrock Launcher
- Most armv6/armv7 software
  - [Minecraft Pi Reborn](https://github.com/Botspot/pi-apps/pull/2493#issuecomment-1836200199)
- Scratch3
- [Flycast](https://github.com/flyinghead/flycast/issues/1288)
- [DOSBox](https://github.com/realnc/dosbox-core/issues/57)
- [btrfs](https://github.com/raspberrypi/bookworm-feedback/issues/136) (should be fixed in newer linux kernels or with newly generated btrfs storage I think.. https://www.spinics.net/lists/linux-btrfs/msg120249.html)
- [Musescore](https://github.com/musescore/MuseScore/issues/20342) - (< 4.2.0)

**Comment by ghollingworth** [comment]
If you find this is a problem, switch to the 4k page size using:

kernel=kernel8.img

in config.txt

**Comment by popcornmix** [comment]
Scratch 3. https://github.com/raspberrypi/bookworm-feedback/issues/91

**Comment by theofficialgman** [comment]
unable to systemd-nspawn 32bit image https://github.com/raspberrypi/bookworm-feedback/issues/120

**Comment by retropieuser** [comment]
Flycast

**Comment by lurch** [comment]
btrfs-convert #136

**Comment by Botspot** [comment]
MuseScore. https://github.com/Botspot/pi-apps/issues/2480

**Comment by Botspot** [comment]
Minecraft Pi

**Comment by JamesH65** [comment]
> Minecraft Pi

Doesn't minecraftPi use Dispmanx for its display, or has that been updated? If it is still Dispmanx, then I am not sure it will work on Bookworm/Pi5 even with 4k pages.

**Comment by theofficialgman** [comment]
> > Minecraft Pi
> 
> Doesn't minecraftPi use Dispmanx for its display, or has that been updated? If it is still Dispmanx, then I am not sure it will work on Bookworm/Pi5 even with 4k pages.

I think what Botspot is referring to is the project based on Minecraft Pi edition called and Minecraft Pi Reborn. It still run the original binary but patches it (somehow, don't really know the technical details) to use more modern display stacks (I think glfw is used), add features and mods, and native arm64 support without armhf multiarch. I can confirm that Minecraft Pi Reborn works on Pi5 Bookworm with 4K pagesize.

**Comment by JamesH65** [comment]
Thanks for the update, I did wonder what had happened to Minecraft Pi. Bizarre that an app like that has some dependency on page size.

**Comment by pelwell** [comment]
Any app that tries to mmap something (hardware, for example, or perhaps RAM that is shared with the firmware) has to ensure that the base address that is mmaped is aligned to the OS page boundaries, and that alignment has now jumped from 4k to 16k.

**Comment by vanfanel** [comment]
@pelwell So that means there is no possible fix at the kernel level, but software has to be adapted instead, right?

**Comment by pelwell** [comment]
The fix at the kernel level is to not use 16kB pages, which you can do with the addition of `kernel=kernel8.img` to config.txt.

**Comment by JamesH65** [comment]
> @pelwell So that means there is no possible fix at the kernel level, but software has to be adapted instead, right?

The best fix would be for people to write software that was page-size independent.  Just requires a bit more effort/thinking when writing it. I think there may be some very edge cases where it's difficult to deal with (Looking above, perhaps file systems with block size < page size), but they are few and far between.

**Comment by theofficialgman** [comment]
> Bizarre that an app like that has some dependency on page size.

@JamesH65 Every single executable file has a dependency on page size (see asahi wiki page on the subject https://github.com/AsahiLinux/docs/wiki/Broken-Software#why-does-not-work-sometimes-mean-instantly-segfault). Older versions of the gold linker only produced 4K pagesize compatible binaries though this was corrected in 2015 https://sourceware.org/legacy-ml/binutils-cvs/2015-10/msg00050.html some old software is of course still affected by that gold linker issue even 2023. Some software manually overwrite the pagesize and that is the list of software you see above.

**Comment by pelwell** [comment]
Understood (it wasn't my comment)

**Comment by mnorrsken** [comment]
jemalloc - bitnami/redis docker image

**Comment by Botspot** [comment]
Cura slicer AppImage https://github.com/smartavionics/Cura

**Comment by dstumbo** [comment]
Polars (python module) because it uses jemalloc. ghollingworth's suggestion of using kernel8.img fixed it for me. I have read elsewhere that ubuntu uses a different page size and does not have the jemalloc issue, but I have not verified it.

**Comment by Widge-5** [comment]
libretro flycast.
(the flycast already mentioned and fixed was flyinghead flycast known as lr-flycast-dev in retropie-setup. I'm referring specifically to lr-flycast which is still affected).

**Comment by koverg70** [comment]
noip.com duc
https://www.noip.com/support/knowledgebase/install-linux-3-x-dynamic-update-client-duc

But you can build it from source using cargo and rust, and it just works.

**Comment by popcornmix** [comment]
Are you saying if you install it by downloading the linked deb file, it works with kernel8.img, but not with kernel_2712.img?
But if you build from source (presumably a newer version?) it works on both?

**Comment by koverg70** [comment]
> Are you saying if you install it by downloading the linked deb file, it works with kernel8.img, but not with kernel_2712.img? But if you build from source (presumably a newer version?) it works on both?

Yes indeed!

**Comment by popcornmix** [comment]
Sounds like it's best reported to noip that updating their deb files would solve this issue.

**Comment by basisbit** [comment]
OvenMediaEngine, because it uses jemalloc (and the RaspberryPi 5 even with 8GB RAM doesn't have enough RAM to fully recomplie it and test if the jemallow configure option fixes all issues).

**Comment by Botspot** [comment]
> OvenMediaEngine, because it uses jemalloc (and the RaspberryPi 5 even with 8GB RAM doesn't have enough RAM to fully recomplie it and test if the jemallow configure option fixes all issues).

Maybe try fewer threads, if possible. Also ZRAM should fix that for you. https://forums.raspberrypi.com/viewtopic.php?t=327238

**Comment by lurch** [comment]
maxima #297

**Comment by kmontocam** [comment]
Running fluent-bit containerized (have tested standalone) also

**Comment by leolivier** [comment]
> jemalloc - bitnami/redis docker image

As well as any "internal" redis installation in images. I install redis in my own image like this:
```
RUN	curl -fsSL https://packages.redis.io/gpg | gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg &&\
		echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" > /etc/apt/sources.list.d/redis.list &&\
		apt-get update &&\
		apt-get install -y redis	&&\
		...
```
and I get a `<jemalloc>: Unsupported system page size` when starting and redis crashes

**Comment by csdivad** [comment]
What about mongo (tcmalloc)? Running its docker image results in
```
1 src/third_party/tcmalloc/dist/tcmalloc/system-alloc.cc:755] MmapAligned() failed - unable to allocate with tag (hint=0x4d80c0000000, size=1073741824, alignment=1073741824) - is something limiting address placement?
1 src/third_party/tcmalloc/dist/tcmalloc/arena.cc:48] CHECK in Alloc: FATAL ERROR: Out of memory trying to allocate internal tcmalloc data (bytes=131072, object-size=640); is something preventing mmap from succeeding (sandbox, VSS limitations)?
```

**Comment by illwieckz** [comment]
Are affected too:

- Google Native Client (virtual machine):
  https://www.chromium.org/nativeclient/
- Daemon (game engine, it uses Native Client to virtualise the game code):
  https://github.com/DaemonEngine/Daemon
- Unvanquished (game, it uses the Dæmon game engine):
  https://unvanquished.net/

Here is the issue on Unvanquished side:

- https://github.com/Unvanquished/Unvanquished/issues/3286

The Native Client virtual machine technology is now deprecated by Google in favor of WebAssembly, unfortunately WebAssembly hasn't reached yet the level of features of Native Client and is then not usable yet for the needs of game engines like Dæmon. That is why the Dæmon game engine still relies on Native Client.

The Native Client loader on ARM is 32-bit only, Google never implemented it for 64-bit, so the 64-bit Dæmon game engine uses the 32-bit NaCl loader, the same way the 64-bit Google Chrome uses the 32-bit NaCl loader.

It is unlikely Google will distribute a new NaCl loader. We cannot exclude that a recompilation may not be enough to fix it, because the loader is known to do some very low-level tricks on memory to implement the isolation.

As a side note, I see that “All Chromium-based applications (pre-102)” are affected, it's possible that when Chromium is rebuilt to work for 16k PageSize kernels, said Chromium would not have the NaCl feature working even if other features are working properly.

**Comment by Hoernchen** [comment]
btrfs is still affected: I can't mount or boot a rpi400 sd card btrfs that was created 3 years ago with the 6.6.74+rpt-rpi-2712 kernel, due to 
```
[ 7926.089598] BTRFS: device label writable devid 1 transid 167933 /dev/sda2 scanned by mount (134985)
[ 7926.091620] BTRFS info (device sda2): first mount of filesystem e5731234-7dbd-4c96-a83b-48f5e5d7b014
[ 7926.091639] BTRFS info (device sda2): using crc32c (crc32c-generic) checksum algorithm
[ 7926.091654] BTRFS info (device sda2): enabling all of the rescue options
[ 7926.091656] BTRFS info (device sda2): ignoring data csums
[ 7926.091657] BTRFS info (device sda2): ignoring bad roots
[ 7926.091659] BTRFS info (device sda2): disabling log replay at mount time
[ 7926.091661] BTRFS info (device sda2): disk space caching is enabled
[ 7926.091663] BTRFS warning (device sda2): v1 space cache is not supported for page size 16384 with sectorsize 4096
[ 7926.092029] BTRFS error (device sda2): open_ctree failed
```

(this was with "-o ro,rescue=all" which does not help either).

**Comment by lurch** [comment]
@popcornmix or @pelwell might be able to confirm, but I wonder if it's the case that a filesystem that was initially created with a 4KB page-size kernel can only later be mounted by a 4KB page-size kernel; and a filesystem that was initially created with a 16KB page-size kernel can only later be mounted by a 16KB page-size kernel? 🤔

**Comment by Botspot** [comment]
Signal Desktop
https://github.com/Botspot/pi-apps/issues/2732

**Comment by kovimilu** [comment]
ceph's OSD doesn't work either, what cephadm would do for the OSD is not working, thus I can't have OSDs managed by cephadm nor can I adopt the OSDs with cephadm if created seperatly

OSD process will SEGV very early (exit code -11)

**Comment by popcornmix** [comment]
Have you reported this to ceph? It is something they will have to fix.
Looks like bug reports are handled through a [mailing list](https://docs.ceph.com/en/latest/rados/troubleshooting/community/).

**Comment by kovimilu** [comment]
> Have you reported this to ceph? It is something they will have to fix. Looks like bug reports are handled through a [mailing list](https://docs.ceph.com/en/latest/rados/troubleshooting/community/).

Hi,

No, i have not.
From the things i found, this doesn't seem like a bug to me, do you think this qualifies as a bug?

**Comment by rsutton1** [comment]
You can add Cloudnative PG controller for Kubernetes: https://github.com/tensorchord/cloudnative-pgvecto.rs/issues/103

**Comment by popcornmix** [comment]
> From the things i found, this doesn't seem like a bug to me, do you think this qualifies as a bug?

Yes. It is a bug that they are assuming the pagesize is 4K rather than using the appropriate API to query the pagesize
(e.g. `getconf PAGESIZE` from command line, or `sysconf(_SC_PAGESIZE)` from C code). But without knowing their software I don't know where that assumption is made.

It is possible they are depending on another library that makes the 4K assumption, in which case the bug report needs to be punted along to them - but you'd need someone from ceph to diagnose if that is the case.

There is nothing raspberry pi can do to make their code work on a 16K pagesize kernel (other than provide a manual option to use the 4K pagesize kernel - which is a workaround rather than a fix).

**Comment by kovimilu** [comment]
> > From the things i found, this doesn't seem like a bug to me, do you think this qualifies as a bug?
> 
> Yes. It is a bug that they are assuming the pagesize is 4K rather than using the appropriate API to query the pagesize (e.g. `getconf PAGESIZE` from command line, or `sysconf(_SC_PAGESIZE)` from C code). But without knowing their software I don't know where that assumption is made.
> 
> It is possible they are depending on another library that makes the 4K assumption, in which case the bug report needs to be punted along to them - but you'd need someone from ceph to diagnose if that is the case.
> 
> There is nothing raspberry pi can do to make their code work on a 16K pagesize kernel (other than provide a manual option to use the 4K pagesize kernel - which is a workaround rather than a fix).

Alright, then i will try to report it as bug in ceph's direction.
By the way, i tried it with a 4KB Kernel, but got the same error message.


this is the error message I get with both kernel page sizes, maybe it it will help go in the right direction:

```
root@ceph-master-1-02:~# ceph orch daemon add osd ceph-master-1-02:/dev/nvme0n1 lvm
Error EINVAL: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/mgr_module.py", line 1809, in _handle_command
    return self.handle_command(inbuf, cmd)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 183, in handle_command
    return dispatch[cmd['prefix']].call(self, cmd, inbuf)
  File "/usr/share/ceph/mgr/mgr_module.py", line 474, in call
    return self.func(mgr, **kwargs)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 119, in <lambda>
    wrapper_copy = lambda *l_args, **l_kwargs: wrapper(*l_args, **l_kwargs)  # noqa: E731
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 108, in wrapper
    return func(*args, **kwargs)
  File "/usr/share/ceph/mgr/orchestrator/module.py", line 1100, in _daemon_add_osd
    raise_if_exception(completion)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 240, in raise_if_exception
    raise e
RuntimeError: cephadm exited with an error code: 1, stderr:Inferring config /var/lib/ceph/105042a8-6324-11ef-bae2-d83addf4a913/mon.ceph-master-1-02/config
Non-zero exit code 1 from /usr/bin/podman run --rm --ipc=host --stop-signal=SIGTERM --net=host --entrypoint /usr/sbin/ceph-volume --privileged --group-add=disk --init -e CONTAINER_IMAGE                                     =quay.io/ceph/ceph@sha256:259cbcf17122953765b8febf2e01682caf11c883bd41ffcea12d2afb88f5b9b5 -e NODE_NAME=ceph-master-1-02 -e CEPH_USE_RANDOM_NONCE=1 -e CEPH_VOLUME_OSDSPEC_AFFINITY=None                                      -e CEPH_VOLUME_SKIP_RESTORECON=yes -e CEPH_VOLUME_DEBUG=1 -v /var/run/ceph/105042a8-6324-11ef-bae2-d83addf4a913:/var/run/ceph:z -v /var/log/ceph/105042a8-6324-11ef-bae2-d83addf4a913:/va                                     r/log/ceph:z -v /var/lib/ceph/105042a8-6324-11ef-bae2-d83addf4a913/crash:/var/lib/ceph/crash:z -v /run/systemd/journal:/run/systemd/journal -v /dev:/dev -v /run/udev:/run/udev -v /sys:/                                     sys -v /run/lvm:/run/lvm -v /run/lock/lvm:/run/lock/lvm -v /:/rootfs -v /etc/hosts:/etc/hosts:ro -v /tmp/ceph-tmp4l5ek_p1:/etc/ceph/ceph.conf:z -v /tmp/ceph-tmpe5a27byv:/var/lib/ceph/bo                                     otstrap-osd/ceph.keyring:z quay.io/ceph/ceph@sha256:259cbcf17122953765b8febf2e01682caf11c883bd41ffcea12d2afb88f5b9b5 lvm batch --no-auto /dev/nvme0n1 --yes --no-systemd
/usr/bin/podman: stderr --> passed data devices: 1 physical, 0 LVM
/usr/bin/podman: stderr --> relative data size: 1.0
/usr/bin/podman: stderr Running command: /usr/bin/ceph-authtool --gen-print-key
/usr/bin/podman: stderr Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new a94b22d3-2fde-48b8-b5d5                                     -0d7d6d89ac95
/usr/bin/podman: stderr Running command: nsenter --mount=/rootfs/proc/1/ns/mnt --ipc=/rootfs/proc/1/ns/ipc --net=/rootfs/proc/1/ns/net --uts=/rootfs/proc/1/ns/uts /sbin/vgcreate --force                                      --yes ceph-4c30d0c2-eb2c-4da2-b056-46f26236de8c /dev/nvme0n1
/usr/bin/podman: stderr  stdout: Physical volume "/dev/nvme0n1" successfully created.
/usr/bin/podman: stderr  stdout: Volume group "ceph-4c30d0c2-eb2c-4da2-b056-46f26236de8c" successfully created
/usr/bin/podman: stderr Running command: nsenter --mount=/rootfs/proc/1/ns/mnt --ipc=/rootfs/proc/1/ns/ipc --net=/rootfs/proc/1/ns/net --uts=/rootfs/proc/1/ns/uts /sbin/lvcreate --yes -                                     l 238467 -n osd-block-a94b22d3-2fde-48b8-b5d5-0d7d6d89ac95 ceph-4c30d0c2-eb2c-4da2-b056-46f26236de8c
/usr/bin/podman: stderr  stdout: Logical volume "osd-block-a94b22d3-2fde-48b8-b5d5-0d7d6d89ac95" created.
/usr/bin/podman: stderr Running command: /usr/bin/ceph-authtool --gen-print-key
/usr/bin/podman: stderr Running command: /usr/bin/mount -t tmpfs tmpfs /var/lib/ceph/osd/ceph-0
/usr/bin/podman: stderr Running command: /usr/bin/chown -h ceph:ceph /dev/ceph-4c30d0c2-eb2c-4da2-b056-46f26236de8c/osd-block-a94b22d3-2fde-48b8-b5d5-0d7d6d89ac95
/usr/bin/podman: stderr Running command: /usr/bin/chown -R ceph:ceph /dev/dm-0
/usr/bin/podman: stderr Running command: /usr/bin/ln -s /dev/ceph-4c30d0c2-eb2c-4da2-b056-46f26236de8c/osd-block-a94b22d3-2fde-48b8-b5d5-0d7d6d89ac95 /var/lib/ceph/osd/ceph-0/block
/usr/bin/podman: stderr Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring mon getmap -o /var/lib/ceph/osd/ceph                                     -0/activate.monmap
/usr/bin/podman: stderr  stderr: got monmap epoch 5
/usr/bin/podman: stderr --> Creating keyring file for osd.0
/usr/bin/podman: stderr Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-0/keyring
/usr/bin/podman: stderr Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-0/
/usr/bin/podman: stderr Running command: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 0 --monmap /var/lib/ceph/osd/ceph-0/activate.monmap --keyfile - --osdspec                                     -affinity None --osd-data /var/lib/ceph/osd/ceph-0/ --osd-uuid a94b22d3-2fde-48b8-b5d5-0d7d6d89ac95 --setuser ceph --setgroup ceph
/usr/bin/podman: stderr --> Was unable to complete a new OSD, will rollback changes
/usr/bin/podman: stderr Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd purge-new osd.0 --yes-i-really-m                                     ean-it
/usr/bin/podman: stderr  stderr: purged osd.0
/usr/bin/podman: stderr --> Zapping: /dev/ceph-4c30d0c2-eb2c-4da2-b056-46f26236de8c/osd-block-a94b22d3-2fde-48b8-b5d5-0d7d6d89ac95
/usr/bin/podman: stderr --> Unmounting /var/lib/ceph/osd/ceph-0
/usr/bin/podman: stderr Running command: /usr/bin/umount -v /var/lib/ceph/osd/ceph-0
/usr/bin/podman: stderr  stderr: umount: /var/lib/ceph/osd/ceph-0 unmounted
/usr/bin/podman: stderr Running command: /usr/bin/dd if=/dev/zero of=/dev/ceph-4c30d0c2-eb2c-4da2-b056-46f26236de8c/osd-block-a94b22d3-2fde-48b8-b5d5-0d7d6d89ac95 bs=1M count=10 conv=fs                                     ync
/usr/bin/podman: stderr  stderr: 10+0 records in
/usr/bin/podman: stderr 10+0 records out
/usr/bin/podman: stderr  stderr: 10485760 bytes (10 MB, 10 MiB) copied, 0.0395423 s, 265 MB/s
/usr/bin/podman: stderr --> Only 1 LV left in VG, will proceed to destroy volume group ceph-4c30d0c2-eb2c-4da2-b056-46f26236de8c
/usr/bin/podman: stderr Running command: nsenter --mount=/rootfs/proc/1/ns/mnt --ipc=/rootfs/proc/1/ns/ipc --net=/rootfs/proc/1/ns/net --uts=/rootfs/proc/1/ns/uts /sbin/vgremove -v -f c                                     eph-4c30d0c2-eb2c-4da2-b056-46f26236de8c
/usr/bin/podman: stderr  stderr: Removing ceph--4c30d0c2--eb2c--4da2--b056--46f26236de8c-osd--block--a94b22d3--2fde--48b8--b5d5--0d7d6d89ac95 (254:0)
/usr/bin/podman: stderr  stderr: Releasing logical volume "osd-block-a94b22d3-2fde-48b8-b5d5-0d7d6d89ac95"
/usr/bin/podman: stderr   Archiving volume group "ceph-4c30d0c2-eb2c-4da2-b056-46f26236de8c" metadata (seqno 5).
/usr/bin/podman: stderr  stdout: Logical volume "osd-block-a94b22d3-2fde-48b8-b5d5-0d7d6d89ac95" successfully removed.
/usr/bin/podman: stderr  stderr: Removing physical volume "/dev/nvme0n1" from volume group "ceph-4c30d0c2-eb2c-4da2-b056-46f26236de8c"
/usr/bin/podman: stderr  stdout: Volume group "ceph-4c30d0c2-eb2c-4da2-b056-46f26236de8c" successfully removed
/usr/bin/podman: stderr  stderr: Creating volume group backup "/etc/lvm/backup/ceph-4c30d0c2-eb2c-4da2-b056-46f26236de8c" (seqno 6).
/usr/bin/podman: stderr Running command: nsenter --mount=/rootfs/proc/1/ns/mnt --ipc=/rootfs/proc/1/ns/ipc --net=/rootfs/proc/1/ns/net --uts=/rootfs/proc/1/ns/uts /sbin/pvremove -v -f -                                     f /dev/nvme0n1
/usr/bin/podman: stderr  stdout: Labels on physical volume "/dev/nvme0n1" successfully wiped.
/usr/bin/podman: stderr --> Zapping successful for OSD: 0
/usr/bin/podman: stderr Traceback (most recent call last):
/usr/bin/podman: stderr   File "/usr/sbin/ceph-volume", line 33, in <module>
/usr/bin/podman: stderr     sys.exit(load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')())
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/main.py", line 41, in __init__
/usr/bin/podman: stderr     self.main(self.argv)
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/decorators.py", line 59, in newfunc
/usr/bin/podman: stderr     return f(*a, **kw)
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/main.py", line 153, in main
/usr/bin/podman: stderr     terminal.dispatch(self.mapper, subcommand_args)
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/terminal.py", line 194, in dispatch
/usr/bin/podman: stderr     instance.main()
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/devices/lvm/main.py", line 46, in main
/usr/bin/podman: stderr     terminal.dispatch(self.mapper, self.argv)
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/terminal.py", line 194, in dispatch
/usr/bin/podman: stderr     instance.main()
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/decorators.py", line 16, in is_root
/usr/bin/podman: stderr     return func(*a, **kw)
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/devices/lvm/batch.py", line 414, in main
/usr/bin/podman: stderr     self._execute(plan)
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/devices/lvm/batch.py", line 432, in _execute
/usr/bin/podman: stderr     c.create(argparse.Namespace(**args))
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/decorators.py", line 16, in is_root
/usr/bin/podman: stderr     return func(*a, **kw)
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/devices/lvm/create.py", line 26, in create
/usr/bin/podman: stderr     prepare_step.safe_prepare(args)
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/devices/lvm/prepare.py", line 196, in safe_prepare
/usr/bin/podman: stderr     self.prepare()
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/decorators.py", line 16, in is_root
/usr/bin/podman: stderr     return func(*a, **kw)
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/devices/lvm/prepare.py", line 278, in prepare
/usr/bin/podman: stderr     prepare_bluestore(
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/devices/lvm/prepare.py", line 59, in prepare_bluestore
/usr/bin/podman: stderr     prepare_utils.osd_mkfs_bluestore(
/usr/bin/podman: stderr   File "/usr/lib/python3.9/site-packages/ceph_volume/util/prepare.py", line 459, in osd_mkfs_bluestore
/usr/bin/podman: stderr     raise RuntimeError('Command failed with exit code %s: %s' % (returncode, ' '.join(command)))
/usr/bin/podman: stderr RuntimeError: Command failed with exit code -11: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 0 --monmap /var/lib/ceph/osd/ceph-0/activ                                     ate.monmap --keyfile - --osdspec-affinity None --osd-data /var/lib/ceph/osd/ceph-0/ --osd-uuid a94b22d3-2fde-48b8-b5d5-0d7d6d89ac95 --setuser ceph --setgroup ceph
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/var/lib/ceph/105042a8-6324-11ef-bae2-d83addf4a913/cephadm.2b9d7d139a9cb40289f2358faf49a109fc297c0a258bde893227c262c30bca8d/__main__.py", line 10700, in <module>
  File "/var/lib/ceph/105042a8-6324-11ef-bae2-d83addf4a913/cephadm.2b9d7d139a9cb40289f2358faf49a109fc297c0a258bde893227c262c30bca8d/__main__.py", line 10688, in main
  File "/var/lib/ceph/105042a8-6324-11ef-bae2-d83addf4a913/cephadm.2b9d7d139a9cb40289f2358faf49a109fc297c0a258bde893227c262c30bca8d/__main__.py", line 2445, in _infer_config
  File "/var/lib/ceph/105042a8-6324-11ef-bae2-d83addf4a913/cephadm.2b9d7d139a9cb40289f2358faf49a109fc297c0a258bde893227c262c30bca8d/__main__.py", line 2361, in _infer_fsid
  File "/var/lib/ceph/105042a8-6324-11ef-bae2-d83addf4a913/cephadm.2b9d7d139a9cb40289f2358faf49a109fc297c0a258bde893227c262c30bca8d/__main__.py", line 2473, in _infer_image
  File "/var/lib/ceph/105042a8-6324-11ef-bae2-d83addf4a913/cephadm.2b9d7d139a9cb40289f2358faf49a109fc297c0a258bde893227c262c30bca8d/__main__.py", line 2348, in _validate_fsid
  File "/var/lib/ceph/105042a8-6324-11ef-bae2-d83addf4a913/cephadm.2b9d7d139a9cb40289f2358faf49a109fc297c0a258bde893227c262c30bca8d/__main__.py", line 6970, in command_ceph_volume
  File "/var/lib/ceph/105042a8-6324-11ef-bae2-d83addf4a913/cephadm.2b9d7d139a9cb40289f2358faf49a109fc297c0a258bde893227c262c30bca8d/__main__.py", line 2136, in call_throws
RuntimeError: Failed command: /usr/bin/podman run --rm --ipc=host --stop-signal=SIGTERM --net=host --entrypoint /usr/sbin/ceph-volume --privileged --group-add=disk --init -e CONTAINER_I                                     MAGE=quay.io/ceph/ceph@sha256:259cbcf17122953765b8febf2e01682caf11c883bd41ffcea12d2afb88f5b9b5 -e NODE_NAME=ceph-master-1-02 -e CEPH_USE_RANDOM_NONCE=1 -e CEPH_VOLUME_OSDSPEC_AFFINITY=N                                     one -e CEPH_VOLUME_SKIP_RESTORECON=yes -e CEPH_VOLUME_DEBUG=1 -v /var/run/ceph/105042a8-6324-11ef-bae2-d83addf4a913:/var/run/ceph:z -v /var/log/ceph/105042a8-6324-11ef-bae2-d83addf4a913                                     :/var/log/ceph:z -v /var/lib/ceph/105042a8-6324-11ef-bae2-d83addf4a913/crash:/var/lib/ceph/crash:z -v /run/systemd/journal:/run/systemd/journal -v /dev:/dev -v /run/udev:/run/udev -v /s                                     ys:/sys -v /run/lvm:/run/lvm -v /run/lock/lvm:/run/lock/lvm -v /:/rootfs -v /etc/hosts:/etc/hosts:ro -v /tmp/ceph-tmp4l5ek_p1:/etc/ceph/ceph.conf:z -v /tmp/ceph-tmpe5a27byv:/var/lib/cep                                     h/bootstrap-osd/ceph.keyring:z quay.io/ceph/ceph@sha256:259cbcf17122953765b8febf2e01682caf11c883bd41ffcea12d2afb88f5b9b5 lvm batch --no-auto /dev/nvme0n1 --yes --no-systemd
```
but i will start gathering the things for the bug report
