### ISSUE TITLE
Help a new pi user set up vnc on a headless 4b....

### ISSUE THREAD

**Issue by furycd001** [raspberrypi/bookworm-feedback#118]
HI guys,

I'm new to the Pi world and have recently acquired a Raspberry Pi 4B that I intend to use in a headless setup. Using the imager utility, I successfully flashed the 64-bit OS with both desktop and software. I also included my username, password, WiFi details, and enabled SSH during the flashing process. The ISO flashed without any issues, and upon connecting the Pi to power and Ethernet, I was able to access it via SSH.

Once connected to the Pi, I executed `sudo raspi-config` and enabled VNC. With VNC enabled, I attempted to connect using **Remmina** on my main Arch system. However, although I was able to connect to the pi, I was met with a tty, instead of the desktop. I'm not certain whether I've missed a step or if **Remmina** is the right VNC viewer for this purpose, but for whatever reason, I can't access the desktop on the Pi.

Like I said, I'm new to the Pi world, so any suggestions and or help would be greatly appreciated....

**Comment by lurch** [comment]
Our documentation is [here](https://www.raspberrypi.com/documentation/computers/remote-access.html) and for these sort of support questions you should be asking for help in the [forums](https://forums.raspberrypi.com/).
