### ISSUE TITLE
Menus in BlueJ and Greenfoot are unusable

### ISSUE THREAD

**Issue by lurch** [raspberrypi/bookworm-feedback#12]
In earlier versions of Bookworm, BlueJ and Greenfoot (as listed in the "Recommended Software" application) weren't installable due to unmet dependencies. They **are** now installable, but when you run them the menus aren't working properly, which (AFAICT) effectively makes them unusable.
AIUI these are maintained by external contributors, so we can't fix them ourself, but perhaps they ought to be removed from the Bookworm version of "Recommended Software" until they're working properly?

**Comment by lurch** [comment]
If I switch to X11 (using `raspi-config`), the menus in BlueJ and Greenfoot _do_ then work properly, so I guess this is just a Wayland + Java GUI problem?

**Comment by spl237** [comment]
BlueJ and Greenfoot have now been dropped from Recommended Software - the maintainers seem to have lost interest.

**Comment by lurch** [comment]
In that close I'll close this issue then :slightly_smiling_face:
