### ISSUE TITLE
Enabling the readonly file system overlay disables desktop autologin, and prevents user from logging in.

### ISSUE THREAD

**Issue by JinShil** [raspberrypi/bookworm-feedback#122]
Steps to reproduce:
1.  Enable desktop autologin and verify that it works.
2.  Enable the readonly file system overlay, and reboot
3. Notice that, after rebooting, the user is no longer autologged into the desktop, and instead is presented with a login dialog window.
4. Further notice that after entering the password, it appears the user is logged in, but then immediately logged out.
5. SSH into the device, disable the readonly file system overlay with raspi-config, and reboot
6. Upon reboot, notice that the user is autologged into the desktop again without issue.

Device tested is a CM4S.

**Comment by lurch** [comment]
Ahhh, possibly the same thing as #22 but just occurring in a slightly different scenario?
(i.e. some part of the "login process" is trying to write to disk, but failing, which causes the login process itself to fail?)

**Comment by JinShil** [comment]
I can no longer reproduce this symptom.  I'm not sure what changed, but it appears to be fixed.  Closing.
