### ISSUE TITLE
Sense HAT Emulator doesn't work

### ISSUE THREAD

**Issue by lurch** [raspberrypi/bookworm-feedback#13]
As installed by "Recommended Software".
If you try to run `sense_emu_gui` from the CLI it gives a big stacktrace about `np.float`.

**Comment by bsimmo** [comment]
Not a new problem
and should be fixed.
https://github.com/astro-pi/python-sense-emu/pull/36 
but not released?

**Comment by lurch** [comment]
I've been informed that this is being worked on; but in the meantime it has been removed from the "Recommended Software" application, so I'll close this issue.

**Comment by steveiliop56** [comment]
Umm I fixed sense hat emu before a long time ago. I tested it and it works with the package I think... (not in bookworm)
