### ISSUE TITLE
Chromium with Wayland crashes when browsing bookmarks in the bookmarks toolbar

### ISSUE THREAD

**Issue by gpi99** [raspberrypi/bookworm-feedback#135]
Chromium with Wayland crashes when browsing bookmarks in the bookmarks toolbar (which is shown below the web address bar).  There's a lot of bookmarks spread over the bookmarks toolbar and 10 sub-folders.  The crash can happen quickly within a few seconds of browsing between the folders, or it may take a bit longer browsing, but usually within a half a minute.  When it crashes the Chromium window just disappears completely.  It has to be relaunched from the menu to start again.  Using a Pi 4.

The Bookmarks were exported from Chromium on Bullseye to a ´bookmarks_date.html´ file and this was imported into Chromium on Bookworm.  Problem present on freshly imaged bookworm, and also with all updates applied today.  No problem observed with the same Chromium with the bookmarks if switching to X11.

**Comment by ghollingworth** [comment]
Cannot reproduce, can you provide bookmarks that reproduce the issue?

**Comment by gpi99** [comment]
Just away from the Pi currently, can grab the file next week.
