### ISSUE TITLE
btrfs-convert doesn't work

### ISSUE THREAD

**Issue by solskogen** [raspberrypi/bookworm-feedback#136]
This is special for the Pi5.
btrfs-convert cannot be used because of the page size.
` btrfs-convert /dev/mmcblk0
btrfs-convert from btrfs-progs v6.2

WARNING: blocksize 4096 is not equal to the page size 16384, converted filesystem won't mount on this system`

Normal mkfs.btrfs works.

**Comment by pelwell** [comment]
Yes, the same is true of F2FS. If btrfs is important to you, put `kernel=kernel8.img` in config.txt to use the Pi 4 kernel.

**Comment by solskogen** [comment]
Yeah, it was more like a FYI rather than a bug. I noticed this when I got my Pi5 yesterday and my old sdcard didn't boot.

**Comment by leifliddy** [comment]
There's a discussion on this topic here:
https://social.treehouse.systems/@marcan/111493984306764821
