### ISSUE TITLE
On Pi5, the DSI Touchscreen needs a way to map (currently) identically named touch controllers to different displays

### ISSUE THREAD

**Issue by 6by9** [raspberrypi/bookworm-feedback#138]
The touch element of the DSI panel comes up as `generic ft5x06 (79)`, however we have now locked the display name DSI-1 to the CAM/DISP0 connector, and DSI-2 to CAM/DISP1.

With the default wayfire.ini containing
```
[input-device:generic ft5x06 (79)]
output = DSI-1
```
if you connect the display to CAM/DISP1 (which is @simon-martin-rpi 's preference with his new cables), then you get DSI-2 and hence an incorrect/no touch assignment. 

I'll have to work on a kernel change to make the touch device names unique (probably including the bus name and address), and the wayfire.ini entry will need to be updated to suit.

**Comment by 6by9** [comment]
https://github.com/raspberrypi/linux/pull/5703 for the kernel side.

I think we'll be wanting
```
[input-device:10-0038 generic ft5x06 (79)]
output = DSI-1

[input-device:6-0038 generic ft5x06 (79)]
output = DSI-1

[input-device:4-0038 generic ft5x06 (79)]
output = DSI-2
```

wayfire.ini has an association for `generic ft5x06 (80)` too. That's a little odd as I thought it was been `generic ft5x06 (00)`, eg https://forums.raspberrypi.com/viewtopic.php?p=2038220#p2038220.
AFAICT We will want the `(00)` variants in wayfire.ini with the same mappings as `(79)`

The existing ones may as well remain to handle those who haven't updated their kernels.

**Comment by 6by9** [comment]
@spl237 Updates required to wayfire.ini please.

**Comment by spl237** [comment]
Done
