### ISSUE TITLE
GitHub Link is not working for me

### ISSUE THREAD

**Issue by MohanRaj1110** [raspberrypi/bookworm-feedback#139]
I'm using the same version of OS on raspberry pi 
link:https://github.com/raspberrypi/bookworm-feedback/issues/41  
In loop command this link is not working for me.

**Comment by ghollingworth** [comment]
This issue makes no sense, does not reference any software and provides no reproduction scenario

**Comment by MohanRaj1110** [comment]
sorry i have raised my issue as individual issue instead of commenting on this issue chat: https://github.com/raspberrypi/bookworm-feedback/issues/41
