### ISSUE TITLE
No on-screen keyboard available in Wayland

### ISSUE THREAD

**Issue by lurch** [raspberrypi/bookworm-feedback#14]
Which means that (unlike in Bullseye) you can't use the Touch Display for typing text-input without a USB keyboard attached.

**Comment by ghollingworth** [comment]
Have you tried squeekboard?

**Comment by lurch** [comment]
I gave that a go on the latest 32-bit Bookworm image on a Pi4, but on Wayland it says:
```

** (squeekboard:1659): WARNING **: 11:00:01.240: No system layout present

** (squeekboard:1659): WARNING **: 11:00:01.298: Could not register to session manager: Cannot invoke method; proxy is for the well-known name “org.gnome.SessionManager” without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag

```
and hangs (so I have to Ctrl-C), and on X11 it says:
```
(squeekboard:1871): Gdk-CRITICAL **: 10:57:50.764: gdk_wayland_display_get_wl_display: assertion 'GDK_IS_WAYLAND_DISPLAY (display)' failed

** (squeekboard:1871): ERROR **: 10:57:50.764: Failed to get display: No such file or directory

```
and quits back to the terminal.

**Comment by steveiliop56** [comment]
Onboard is the best option.

**Comment by lurch** [comment]
> Onboard is the best option.

That doesn't work with the Wayland desktop - as soon as you click on one of the keys the whole application just quits.

**Comment by steveiliop56** [comment]
I think it works... Not sure tho will try again...

**Comment by ghollingworth** [comment]
No onboard won't work with Wayland (so won't work on Pi 4 or Pi 5), it displays fine (because it is using the XWayland backend) but is trying to use an X backend to send the keys...

It seems the answer is:

sudo apt install wvkbd

**Comment by steveiliop56** [comment]
Is there something better? This keyboard is a bit trash and the switches doesn't work...

**Comment by thisisgregm** [comment]
Did someone manage to make wvkbd popping out automatically when a text box is selected?
I customize it and it looks OK-ish now, but each time I need it I need to press an icon to show / hide it. When in a  browser fullscreen mode - the icon is obviously not visible.

**Comment by steveiliop56** [comment]
Nope but I have found a solution I am happy with. I created a small menu item to open the keyboard with a button. Just open the menu editor and create a new item (I created it in help). Then for the command add this ```sh -c "pkill wvkbd-mobintl || wvkbd-mobintl -L 200"``` (the 200 is the size in pixels). After you do that you will have a button in the menu you selected and when you click it the keyboard appears if you click it again it disappears.

**Comment by thisisgregm** [comment]
Thank you @steveiliop56 - this is what I found as well (on the official forums). Maybe it was your post there, not sure. I use full screen browser window a lot, so the button is then not visible :(

**Comment by steveiliop56** [comment]
Yeah it was my comment probably. I think a user in the forums managed to do it with a swipe gesture

**Comment by AgentRev** [comment]
I'm somewhat flabbergasted that RPiOS doesn't ship with a pre-installed onscreen keyboard, requiring a physical keyboard is quite impractical

**Comment by thisisgregm** [comment]
Yep, but well...

As a part of the update - I've managed to make partially squeekboard working (another keyboard program - looks modern and it's easy to configure, pops up automatically via dbus). Partially, because it work fine on Firefox, but not on the full screen. Couldn't make it work on Chromium (full or non full screen). Squeekboard also works with no problems with text editor, terminal, etc. Wouldn't be surprised if it will be included in future Raspberry Pi OS releases.

In the meantime I also tried the latest Ubuntu. Funny enough I realized that their keyboard is based on squeekboard. Managed to make this working on Firefox (full and non full screen). Also doesn't work on Chromium (either snap or deb install).

**Comment by ghollingworth** [comment]
We've been looking into squeekboard on Wayland:

sudo apt install squeekboard
sudo apt install dconf-editor

and then go into org/gnome/desktop/a11y/applications and turn “screen-keyboard-enabled” on

It seems to work in Firefox, but Chromium doesn't seem to work at the moment...  Usual problem, GTK doesn't draw the text entry box so squeekboard doesn't know you are trying to enter keystrokes.  Will need some looking into...

**Comment by BlackRockCity** [comment]
@ghollingworth I followed your instructions, rebooted and no luck. Running latest Raspberry Pi OS desktop Bookworm 64 bit kernel 6.6.31 released 5-29-24.

When I tap in a text field in Firefox or Chrome, no OSK is shown. 

Edit: Ah, the missing step was to type squeekboard into the terminal to launch the keyboard. Yes it works in Firefox! this is promising. I've searched everywhere for an OSK that will show/hide when entering/exiting a textfield in a kiosk.

Also, note to newbs: dconf Editor will be located in your Desktop menu > System Tools > dconf Editor.

**Comment by steveiliop56** [comment]
@BlackRockCity you may be interested in my previous comment:

> Nope but I have found a solution I am happy with. I created a small menu item to open the keyboard with a button. Just open the menu editor and create a new item (I created it in help). Then for the command add this ```sh -c "pkill wvkbd-mobintl || wvkbd-mobintl -L 200"``` (the 200 is the size in pixels). After you do that you will have a button in the menu you selected and when you click it the keyboard appears if you click it again it disappears.

**Comment by BlackRockCity** [comment]
@steveiliop56 Thanks, but the squeekboard solution has automatic show/hide when entering a text field in Firefox. There is no need for buttons, menus, or scripts to get the keyboard to show up! Try it out, it works!

**Comment by steveiliop56** [comment]
Oh didn't know that, I will give it a try!

**Comment by nguyenlamlll** [comment]
Hi @BlackRockCity, how do you get `squeekboard` to work with Firefox in kiosk mode?
I've tried running `squeekboard` on one terminal and `firefox—-kiosk "my.web"` on another terminal. But then the rendering got really buggy/frozen, like in the picture below.
![image](https://github.com/user-attachments/assets/38790868-2f1f-41f9-b1f2-c1086a5259ff)

**Comment by steveiliop56** [comment]
That's a lot of cursors.

**Comment by thisisgregm** [comment]
I've just figured it out that I can install OS Lite and add XFCE (which I already us on other Linux machines, so I'm familiar with it anyway), add OnBoard keyboard and other stuff I need. Luckily XFCE still uses Xorg, not Wayland.
I don't know why I didn't think about it before.
This is the way for everyone who desperately needs OnBoard keyboard..

**Comment by sulincix** [comment]
https://gitlab.com/turkman/devel/sources/ukbd

try this. I supports wayland

**Comment by steveiliop56** [comment]
By the way raspberry pi os now has a built-in on screen keyboard for touchscreens so, the best idea would be to use that.

**Comment by lurch** [comment]
> By the way raspberry pi os now has a built-in on screen keyboard for touchscreens so, the best idea would be to use that.

Indeed; and we've made a bunch of tweaks to it too, so that it better integrates into Raspberry Pi OS https://github.com/raspberrypi-ui/squeekboard/commits/master
