### ISSUE TITLE
pigpiod crash

### ISSUE THREAD

**Issue by sgalke** [raspberrypi/bookworm-feedback#150]
systemctl status pigpiod:

"Sorry, this system does not appear to be a raspberry pi. |
Nov 21 12:08:53 bookworm64 pigpiod[771]: |aborting."

**Comment by sgalke** [comment]
forgot to mention: RPi 5B

**Comment by pelwell** [comment]
This is known, and the author is aware:
* https://github.com/joan2937/pigpio/issues/586
* https://github.com/joan2937/pigpio/issues/589
