### ISSUE TITLE
No available on screen keyboard.

### ISSUE THREAD

**Issue by steveiliop56** [raspberrypi/bookworm-feedback#153]
Hello,

All the keyboards that we used to use in debian bullseye (matchbox, onboard etc.) don't work in debian bookworm. [Here](https://github.com/raspberrypi/bookworm-feedback/issues/14) the xvkbd keyboard was suggested but when I tried it on a fresh install it failed with the only error being: ```Cannot convert string "some font names" to type FontStruct```

**Comment by steveiliop56** [comment]
Found the sticky post on forums.

**Comment by acolomb** [comment]
> Found the sticky post on forums.

What sticky post please?

Is there any place where an update will be announced once the issue is resolved that the OSK doesn't open automatically when focusing a text field?

**Comment by lurch** [comment]
See https://github.com/raspberrypi/documentation/issues/3171#issuecomment-2056812752

**Comment by qmf-industrialshields** [comment]
I had the same issue when using node-red dashboard 2 in bookworm. That's why I ended up creating a very simple lightweight virtual keyboard: https://github.com/qmf-industrialshields/nodered-dashboard-vkeyboard/tree/main

**Comment by lurch** [comment]
@qmf-industrialshields Cool.

For the benefit of anybody else reading this old issue, note that Bookworm now includes `squeekboard` which works automatically with the Raspberry Pi touchscreens https://www.raspberrypi.com/documentation/accessories/touch-display-2.html#use-an-on-screen-keyboard
