### ISSUE TITLE
QT6 webengine not available on 32bit PiOS

### ISSUE THREAD

**Issue by theofficialgman** [raspberrypi/bookworm-feedback#157]
https://bugs.launchpad.net/raspbian/+bug/2043742

I have filed a bug at raspbian as this is due to build failures with QT6 webengine. The generated symbols do not match since the name of the package has changed. Should be a simple enough fix for anyone knowledgeable enough to patch the symbols file or skip this check.

Posting here for greater visibility as there has been no response in over two weeks from posting as well as to provide a github issue to link to for other projects.

**Comment by lurch** [comment]
Closing this issue, as it's an issue in upstream Raspbian and thus not something that we'll be fixing ourselves.

> as well as to provide a github issue to link to for other projects.

Feel free to add additional comments/links to this issue.
