### ISSUE TITLE
Purging Geany leaves residue

### ISSUE THREAD

**Issue by by** [raspberrypi/bookworm-feedback#158]
During `apt purge geany`, the file `/usr/share/raspi-ui-overrides/applications/geany.desktop` does not get deleted, so the icon still resides in the pull-down menu.

**Comment by XECDesign** [comment]
@spl237 I think some .desktop files there are missing a TryExec line.

**Comment by JinShil** [comment]
Duplicate of https://github.com/RPi-Distro/raspberrypi-ui-mods/issues/47

**Comment by lurch** [comment]
Thanks @JinShil , closing this as a duplicate.
