### ISSUE TITLE
on pi zerow with bookwork, serial1 points to ttyAMA0 when disable-bt overlay is loaded

### ISSUE THREAD

**Issue by stevenjowens** [raspberrypi/bookworm-feedback#159]
Logs attached.
If I point my python script directly at /dev/ttyAMA0 it works.
But serial0 is not properly created.

[config.txt](https://github.com/raspberrypi/bookworm-feedback/files/13575836/config.txt)
[dmesg.txt](https://github.com/raspberrypi/bookworm-feedback/files/13575837/dmesg.txt)
[dtc_proc_device_tree.txt](https://github.com/raspberrypi/bookworm-feedback/files/13575838/dtc_proc_device_tree.txt)
[vcdbg.log](https://github.com/raspberrypi/bookworm-feedback/files/13575839/vcdbg.log)

**Comment by pelwell** [comment]
This has been fixed already - you just need to update:
```
$ sudo apt update
$ sudo apt install raspberrypi-sys-mods
# Or to update everything:
$ sudo apt upgrade
```
Alternatively, if you aren't invested in the current image, you can install the just-released 2023-12-05 image.

**Comment by stevenjowens** [comment]
Thanks!
