### ISSUE TITLE
Window Partly Vanishes When Dragging Between Screens

### ISSUE THREAD

**Issue by Y4200** [raspberrypi/bookworm-feedback#163]
Fully patched Pi 5.  When dragging a window between screens, the leading edge vanishes.  The window re-appears when the mouse pointer crosses the boundary of the screens or perhaps a centimetre before.

**Comment by spl237** [comment]
Known issue with wayfire - as it doesn't affect usability, this is a wontfix until the wayfire developers decide to do so!
