### ISSUE TITLE
Not able to schedule on off

### ISSUE THREAD

**Issue by 1a2a3a1q2s3c** [raspberrypi/bookworm-feedback#164]
Hi all

running bookworm on rpi 5.
I am not able to find a solution to schedule the display to turn off and on at a specific time via cron job.

am able to simulate the on off via wlr randr on off via command but not able to schedule it in cron.

sudo nano /etc/crontab

**Comment by popcornmix** [comment]
This is better asked in the forums, as it is purely a question of how to run commands from cron with the right user/environment.

It is not a problem with RPiOS bookworm (you get exactly the same behaviour on any linux platform).
