### ISSUE TITLE
rpi-imager 1.8.3 requires uuid in the booted IMG but it's AWOL in Lite

### ISSUE THREAD

**Issue by gitbls** [raspberrypi/bookworm-feedback#165]
At least on the 2023-12-05 Lite IMGs, rpi-imager's boot time configurator script, /lib/raspberrypi-sys-mods/imager-custom, uses `uuid`, but the uuid package is not installed in Lite.

Things appear to work correctly if uuid is apt-installed before booting.

The `mini-nspawn` script at https://forums.raspberrypi.com/viewtopic.php?p=2166360#p2166360 can be used to install it in the IMG or SD card until the provided IMGs are updated to include uuid.

**Comment by lurch** [comment]
Duplicate of https://github.com/raspberrypi/rpi-imager/issues/749
