### ISSUE TITLE
[Regression] Broken button icons on gnome apps and gedit

### ISSUE THREAD

**Issue by qrp73** [raspberrypi/bookworm-feedback#170]
It happens about a week ago after some apt update, button icons disappeared and now there is just empty space. 
I thought it will be noticed and fixed soon, but it seems that no one notice it yet...

Yesterday I also tested it on a clean Bookworm aarch64 install with latest updates and this bug is reproduced.

## Steps to reproduce:
1) install gedit and some gnome apps:
```
sudo apt update && sudo apt install gnome-calculator gnome-clocks gedit
```
2) Open installed apps

Expected result: button icons are properly displayed 

Actual result: button icons are missing, empty space is displayed (it worked ok about 2-3 weeks ago before some update)

## Screenshot
![20231213_07h16m01s_grim](https://github.com/raspberrypi/bookworm-feedback/assets/46676744/25ddd697-79cc-4e30-adc0-90ff1502b9d6)

**Comment by lurch** [comment]
I can confirm this behaviour on both 32-bit and 64-bit Bookworm. @spl237 is now on holiday, but I'll ask him to take a look after Christmas.

**Comment by lurch** [comment]
It looks like this also affects the installed-by-default mousepad application.

1. Launch Accessories -> Text Editor
2. Click File -> New
3. Missing close-icons on the tabs:
![image](https://github.com/raspberrypi/bookworm-feedback/assets/476186/afc9b0e2-8016-402f-91e7-df0dff9904f6)
![image](https://github.com/raspberrypi/bookworm-feedback/assets/476186/3d56c345-9339-4102-a21e-5e271a410c22)
![image](https://github.com/raspberrypi/bookworm-feedback/assets/476186/383cb99c-0cb1-4737-a166-84bc3f22a51c)
(the tooltips appear when I mouse-hover over where the close-icons _would_ be)

**Comment by spl237** [comment]
This is caused by applications which use the window-close icon, which is chiefly intended for use as the close button on a window headerbar, for other purposes. Due to various tedious technicalities within GTK, in order to get various other features working correctly with the new themes, this icon is now actually transparent (and in its intended location on a window headerbar, is replaced with two other icons, window-close-hover and window-close-nohover).

It looks as if multiple applications use this icon in places where they really shouldn't, so I'll have to change the way this works. I can see a way to make it work without changing this icon - it's a moderately nasty hack, but it will work. I'll look at it in the new year.

**Comment by spl237** [comment]
OK, fix now uploaded to apt - should be available once things have rebuilt in the repos.

And now I am definitely on Christmas holiday - I only fixed this one now because I was a bit bored... ;)

**Comment by spl237** [comment]
Changes to fix this are now in apt - updating should fix it.

**Comment by lurch** [comment]
Thanks Simon. That fixes all the "close" icons, but there's still two icons (I guess these might be custom minimise & maximise icons) that are missing for gnome-clocks and gnome-calculator.
![image](https://github.com/raspberrypi/bookworm-feedback/assets/476186/737721bf-884f-421e-9b1f-ccbd136dbb4a)

Enjoy your holiday! :christmas_tree:

**Comment by spl237** [comment]
Oh for crying out loud - bloody Gnome! How the hell have they managed to do that? That's presumably a completely custom header bar which is neither the GTK one, the libhandy one, nor one created using standard buttons. None of those were good enough, in spite of the fact that they designed all of them - no, let's create yet another one. Give me strength...

I'm half-inclined to leave that broken, frankly - they aren't even obeying their own standards. I suspect a similar hack will fix it, though - I'll have a look.

**Comment by spl237** [comment]
OK, newly patched versions of relevant packages now uploaded to the repo - should appear in a few hours. I've made the minimize and maximize icons behave exactly the same as the close icon, so they now have separate overrides if needed.

**Comment by lurch** [comment]
Can confirm that this is all displaying correctly now :+1:
