### ISSUE TITLE
New update segmentation fault.

### ISSUE THREAD

**Issue by steveiliop56** [raspberrypi/bookworm-feedback#175]
Hello,

After the new update libc-bin fails. Digging into it I found out ldconfig fails with segmentation fault. The image is brand new raspberry pi os 64 bit.

**Comment by XECDesign** [comment]
Seems okay on this end. Is there any more information that might help trigger the problem.

**Comment by steveiliop56** [comment]
It's just the newest and greatest raspberry pi os 64bit. Just tried to update... Literally I didn't do anything else other than this:

```sudo apt update && sudo apt full-upgrade -y```

**Comment by lurch** [comment]
What model of Raspberry Pi are you running on? Are you booting from SD card? How big is your SD card? Do you have any additional hardware connected to your Pi? Are you using one of the official PSUs?

**Comment by steveiliop56** [comment]
So booting of a USB2 SD card reader with a 32gb SD card (yeah I know USB2 but works fine) attached I have a dsi screen, a camera and a pimoroni fanshim (screen not official, camera module v3) and no low voltage warnings of any kind. I was just trying to test bookworm out before switching to it.

**Comment by steveiliop56** [comment]
Hmm worked the third try after I reinstalled the os. I think it may have been that stupid usb2 adaptor. Anyway closing...
