### ISSUE TITLE
CE0 and CE1 no longer usable on the Pi 5 in Python

### ISSUE THREAD

**Issue by makermelissa** [raspberrypi/bookworm-feedback#179]
I'm not 100% sure this is the correct place, but since the Python error is an OSError, it seems to make sense. 

When trying to access CE0 or CE1 via Python libgpiod bindings, I get `OSError: [Errno 16] Device or resource busy`. It works fine on a Pi 4 using the exact same SD card, so it seems to be a combination of OS and Hardware. If I try using gpiozero, I get "GPIO busy", which is essentially the same error.

I am just trying to run a simple script to toggle the GPIO on and off.

I have no device tree overlays loaded and using the lite version of the OS. SPI is enabled, but not actively being used.

**Comment by makermelissa** [comment]
I forgot to mention I have SPI enabled and can access the GPIO when it is disabled, but then SPI isn't available.

**Comment by makermelissa** [comment]
I did find a potential solution:
1. I added dtoverlay=spi0-0cs to the bottom of /boot/firmware/config.txt
2. I rebooted

After that code worked.

**Comment by URL42** [comment]
@makermelissa Is that all you did? I have the same error when trying to use an Adafruit EYESPI beret for a display and still get the same error for the CE0. Nothing else could be using that pin...But when I run gpioinfo I see CE0 and CE1 are in use...

Tried your fix/reboot and still get the error...

**Comment by URL42** [comment]
oooh I wonder if [this](https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/spi-sensors-devices#reassigning-or-disabling-the-spi-chip-enable-lines-3097985) is the solution? I haven't done this before so am worried I will mess up my gpio pins...

**Comment by makermelissa** [comment]
Yep, I updated that script so you can disable their usage by the OS. All it does is place the correct dtoverlay into the config along with parameters if needed. You can always just remove the dtoverlay from the config and it will go back to normal.

**Comment by URL42** [comment]
Got it, thank you. Unfortunately that line alone in the config.txt file didn't seem to solve the issue for me.

**Comment by URL42** [comment]
Actually never mind, I reloaded the Blinka library and it worked like a charm! Thank you for posting this Melissa! I thought I was going crazy...

**Comment by lurch** [comment]
Sounds like this has been solved / worked-around? So closing...
