### ISSUE TITLE
Raspbian bookworm 

### ISSUE THREAD

**Issue by Smiril** [raspberrypi/bookworm-feedback#195]
I got a huge hung on a raspberry pi 4  64Bit
Os: raspbian bookworm 64Bit 
The only app that runs is cubicSDR and after starting the app(load hackrf and a freq) it seems to hung

not clickable on anything on the desktop 

it just freezes

**Comment by lurch** [comment]
That sounds like a problem you need to report to the cubicSDR developers?

**Comment by Smiril** [comment]
That’s not in Debian 12 with cubicSDR

only raspbian

**Comment by popcornmix** [comment]
raspbian is probably not what you mean (raspbian is a 32-bit build of debian, not handled by Raspberry Pi itself).
RPiOS is the name of the OS images produced by Raspberry Pi.

But cubicSDR is not RPiOS or raspbian specific - it is a debian package:
https://packages.debian.org/bookworm/cubicsdr

But support for the package is probably best handled here: https://github.com/cjcliffe/CubicSDR/issues

Possibly this is related? https://github.com/cjcliffe/CubicSDR/issues/979

But I've never used cubicSDR so cannot help more.

**Comment by lurch** [comment]
Closing this in favour of the upstream issue.
