### ISSUE TITLE
broken font glyphs on bless app window

### ISSUE THREAD

**Issue by qrp73** [raspberrypi/bookworm-feedback#209]
Steps to reproduce:
1) install bless hex editor:
```sudo apt install bless```
2) open some text file with bless

Expected result: normal window content is displayed with hex content of the file

Actual result: broken glyphs are displayed:
![20240211_06h47m42s_grim](https://github.com/raspberrypi/bookworm-feedback/assets/46676744/b6d7bef0-2e69-46f6-a5a1-0262dba382f4)

**Comment by lurch** [comment]
It looks like `bless` is a [Mono](https://www.mono-project.com/) application, so I wonder if this might be a "mono not properly supporting Wayland" issue, similar to how #199 ended up being a "java not properly supporting Wayland" issue?

**Comment by qrp73** [comment]
Yes, it is Mono application, but as I see there is nothing in mono which cannot support Wayland. 
But it uses binding for GTK+, so it seems that the issue is due to [GTK+](https://www.gtk.org/) don't support Wayland. 
Or raspberry pi implementation of Wayland don't support GTK+ properly.

**Comment by spl237** [comment]
This should now be fixed if you update.
