### ISSUE TITLE
Official 7-inch touchscreen + Pi5: When closing the chromium browser, the desktop crashed and entered the login interface

### ISSUE THREAD

**Issue by RayXxxxxx** [raspberrypi/bookworm-feedback#214]
When closes the chromium browser, the desktop crashes and enters the login interface.

**Comment by RayXxxxxx** [comment]
Description:
  When I try to close the chromium browser by touching exit, the desktop turns black, and then jump to login interface. And I found that the same problem would happen when I touched the title bar many times. I did the same in Firefox and everything works fine

Kernel Version:  6.1.58-rpi7-rpi-2712

OS:
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"


config.txt:
```sh
# For more options and information see
# http://rptl.io/configtxt
# Some settings may impact device functionality. See link above for details

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

# Additional overlays and parameters are documented
# /boot/firmware/overlays/README

# Automatically load overlays for detected cameras
camera_auto_detect=1

# Automatically load overlays for detected DSI displays
display_auto_detect=1

# Automatically load initramfs files, if found
auto_initramfs=1

# Enable DRM VC4 V3D driver
dtoverlay=vc4-kms-v3d
max_framebuffers=2

# Don't have the firmware create an initial video= setting in cmdline.txt.
# Use the kernel's default instead.
disable_fw_kms_setup=1

# Run in 64-bit mode
arm_64bit=1

# Disable compensation for displays with overscan
disable_overscan=1

# Run as fast as firmware / board allows
arm_boost=1

[cm4]
# Enable host mode on the 2711 built-in XHCI USB controller.
# This line should be removed if the legacy DWC2 controller is required
# (e.g. for USB device mode) or if USB support is not required.
otg_mode=1

[all]
dtoverlay=vc4-kms-dsi-7inch
```

Logs:
[+0.00s] DEBUG: Logging to /var/log/lightdm/lightdm.log
[+0.00s] DEBUG: Starting Light Display Manager 1.26.0, UID=0 PID=3337
[+0.00s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/01_debian.conf
[+0.00s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf
[+0.00s] DEBUG: Registered seat module local
[+0.00s] DEBUG: Registered seat module xremote
[+0.00s] DEBUG: Registered seat module unity
[+0.00s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager
[+0.00s] DEBUG: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
[+0.00s] DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
[+0.01s] DEBUG: Monitoring logind for seats
[+0.01s] DEBUG: New seat added from logind: seat0
[+0.01s] DEBUG: Seat seat0: Loading properties from config section Seat:*
[+0.01s] DEBUG: Seat seat0 has property CanMultiSession=no
[+0.01s] DEBUG: Seat seat0: Starting
[+0.01s] DEBUG: Seat seat0: Creating user session
[+0.01s] DEBUG: Loading users from org.freedesktop.Accounts
[+0.01s] DEBUG: User /org/freedesktop/Accounts/User1000 added
[+0.13s] DEBUG: Seat seat0: Creating display server of type wayland
[+0.13s] DEBUG: Using VT 7
[+0.13s] DEBUG: Launching process 3402: /usr/share/dispsetup.sh
[+0.13s] DEBUG: Process 3402 exited with return value 0
[+0.13s] DEBUG: Seat seat0: Exit status of /usr/share/dispsetup.sh: 0
[+0.13s] DEBUG: Seat seat0: Display server ready, starting session authentication
[+0.13s] DEBUG: Session pid=3404: Started with service 'lightdm-autologin', username 'pi'
[+0.13s] DEBUG: Acquired bus name org.freedesktop.DisplayManager
[+0.13s] DEBUG: Registering seat with bus path /org/freedesktop/DisplayManager/Seat0
[+0.15s] DEBUG: Session pid=3404: Authentication complete with return value 0: Success
[+0.15s] DEBUG: Seat seat0: Session authenticated, running command
[+0.15s] DEBUG: Registering session with bus path /org/freedesktop/DisplayManager/Session0
[+0.15s] DEBUG: Session pid=3404: Running command /etc/X11/Xsession /usr/bin/wayfire-pi
[+0.15s] DEBUG: Creating shared data directory /var/lib/lightdm/data/pi
[+0.15s] DEBUG: Session pid=3404: Logging to .xsession-errors
[+0.18s] DEBUG: Activating VT 7
[+0.19s] DEBUG: Activating login1 session 7
[+0.20s] DEBUG: Seat seat0 changes active session to 7
[+0.20s] DEBUG: Session 7 is already active

**Comment by RayXxxxxx** [comment]
Here's a video that better describes the problem

https://drive.google.com/file/d/1SbIrq_oAtysVTNHrRZfg8ixOwkbRKnIO/view?usp=sharing

**Comment by 6by9** [comment]
Thanks for the report. This had been noted internally and is already being investigated.

**Comment by spl237** [comment]
This should now be fixed if you update from apt.

**Comment by RayXxxxxx** [comment]
Thanks, problem solved!
