### ISSUE TITLE
Launcher bar configuration menu is gone

### ISSUE THREAD

**Issue by nielsbaloe** [raspberrypi/bookworm-feedback#226]
How can I rearrange the icons in the Launcher in the menu bar?

 If I right-click the menu bar, choose "Add/Remove Plugins", select launcher, click "Configure", then it only lets me define a pixel width now, but not anymore the good old settings where I could add/remove/reorder launcher icons. Where did the access to these settings disappear to?

**Comment by lurch** [comment]
See https://github.com/raspberrypi-ui/wf-panel-pi

**Comment by spl237** [comment]
You can't reorder the launcher icons directly any more - the way the new panel works means this is not as yet supported.

To work around it, just remove the icons by right-clicking them, and add them back in the order you want by selecting from the menu, right clicking and choosing Add to Launchbar.
