### ISSUE TITLE
Dragging file(s) into the desktop or a folder is not possible anymore

### ISSUE THREAD

**Issue by nielsbaloe** [raspberrypi/bookworm-feedback#227]
If I drag files fromout xarchiver or fileroller to the desktop or into a folder, it should decompress the selected files&folders, but nothing happens instead. 

I guess the archivers do not acknowledge the new desktop/folders yet.

**Comment by lurch** [comment]
> I guess the archivers do not acknowledge the new desktop/folders yet.

This sounds like something that you should ask those upstream projects about?

**Comment by nielsbaloe** [comment]
I will do so. Until that time I will not replace all my raspberry pi 4's to 5's because I really need this to work. There are too little things that just don't work right now.

**Comment by lurch** [comment]
Closing as an upstream issue.
