### ISSUE TITLE
Codec-Zero doesn't work

### ISSUE THREAD

**Issue by lurch** [raspberrypi/bookworm-feedback#24]
The instructions at https://www.raspberrypi.com/documentation/accessories/audio.html#extra-codec-zero-configuration no longer work, see https://github.com/raspberrypi/documentation/issues/2937

**Comment by pelwell** [comment]
I'm don't think that's a failure - it's just an ugly success.

**Comment by lurch** [comment]
Yeah, I've now come to to the conclusion that the particular Codec-Zero board I was testing with is somehow broken, which is why I misinterpreted the "ugly success" as a "fatal error" :roll_eyes: 
Now doing some final testing on a working board, and will close this issue if appropriate.

**Comment by lurch** [comment]
Yup, can now confirm that Codec-Zero works fine on both Bookworm and Raspberry Pi 5.
