### ISSUE TITLE
ddrescue fails to run

### ISSUE THREAD

**Issue by psfales** [raspberrypi/bookworm-feedback#240]
Trying to run the stock "dd_rescue" on bookworm.

Running into two problems.   The first may be working as designed, but for some reason, the package is named "ddrescue" and the command is named "dd_rescue".   But more importantly, when I run the command, I get this error:

$ dd_rescue 
-bash: /usr/bin/dd_rescue: cannot execute: required file not found

I've tested this on two different systems, both of which have no other known problems, so I don't think it's file system corruption or anything like that.   Part of the reason for this report is to confirm whether other people are seeing it as well, or if it's just me!

To reproduce:

1) Install the package:
$ sudo apt install ddrescue

2) run the command:
$ dd_rescue

Expected result:  the dd_rescue help message

Actual result:   -bash: /usr/bin/dd_rescue: cannot execute: required file not found

**Comment by XECDesign** [comment]
This hits 3 separate issues:

1) Debian package names can't have underscores so if somebody creates some_tool, it would have to be packaged as some-tool or sometool. That's not really a bug, just a "feature" of Debian using `_` as a delimiter.

2) Raspbian does something a bit strange. When they add a new release, they import all the packages from a previous release. ddrescue should not exist in the bookworm repo at all, but this is outside of our control. You can report the issue [here](https://bugs.launchpad.net/raspbian/+bugs).

3) Following on from above, ddrescue is not the package you're really after. I believe gddrescue is the package that should be used, according to [this bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=677101).
