### ISSUE TITLE
Does TV-HAT work?

### ISSUE THREAD

**Issue by lurch** [raspberrypi/bookworm-feedback#25]
Do the instructions at https://www.raspberrypi.com/documentation/accessories/tv-hat.html still work okay on Bookworm?

**Comment by lurch** [comment]
I guess this also depends on #2

**Comment by XECDesign** [comment]
I don't know about those specific instructions, but the HAT worked when I was testing the new tvheadend package.

**Comment by popcornmix** [comment]
> OMXPlayer, supplied with Raspberry Pi OS, also supports viewing TV streams from tvheadend

is out of date.

**Comment by lurch** [comment]
Closing this, in preference to https://github.com/raspberrypi/linux/issues/5953
