### ISSUE TITLE
Right click on 1password icon in panel will crash panel (Wayland)

### ISSUE THREAD

**Issue by josefwegner** [raspberrypi/bookworm-feedback#250]
Hi,

When running Wayland and starting 1password, you can very easily crash the panel by right right clicking on the 1password icon on the right of the panel. Left clicks are fine.

Steps to reproduce:
- Enable Wayland in raspi-config
- Log in
- Start 1password
- Right click on 1password icon on top right

Outcome:
- Panel crashes and restarts

System:
Raspberry Pi 5 8GB
Raspberry Pi OS Bookworm
All updates
Linux pi5 6.6.28+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.28-1+rpt1 (2024-04-22) aarch64 GNU/Linux

**Comment by josefwegner** [comment]
Does not happen anymore with labwc

**Comment by lurch** [comment]
Thanks for confirming :+1:
