### ISSUE TITLE
gstreamer-1.22.0 ximagesink is broken on R. Pi: needs a tiny backport from 1.22.10

### ISSUE THREAD

**Issue by fduncanh** [raspberrypi/bookworm-feedback#257]
When touchscreen support was added to ximagesink (only needed in cases where the monitor doesn't support xvimagesink, typically seen on small 400x860 screens often used with Pi .... )   an initialization was not done, which always causes a segfault on the pi with bookworm's gstreamer1.0-plugins-base, when ximagesink starts.

* the patch needed is just to add   " = {0}"  on  one line, and is already merged into gstreamer.

*see https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/6631/diffs

**Comment by XECDesign** [comment]
We don't currently patch gstreamer in bookworm, so it's a stock Debian package. If the bug is filed and fixed there, it will flow down into Raspberry Pi OS.

@6by9, or does this look like a high priority issue that we should fix on our end?

**Comment by 6by9** [comment]
It's not a terribly high priority fix in my book.

You've flagged if for a backport in your comment at https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3470#note_2371743. Is that going to happen? If so then it should appear eventually as Debian pick up the 1.22 update. Otherwise it's possibly worth flagging it on the Debian bug tracker as a potential patch they might wish to carry.

**Comment by fduncanh** [comment]
It was backported from gstreamer development to 1.24.3 and 1.22.12   Debian won't use 1.22.12.   Next Debian major release will be OK since its fixed in 1.24.3 and newer (in Sid)

I will try and get Debian bugs to backport it to Bookworm fixes (for 1.22.0)  but who knows?   Its a very small fix, and a patch is available on our site, with instructions for users.   https://github.com/FDH2/UxPlay/wiki/patches-for-(1)-broken--videoflip-method-and-(2)-broken-ximagesink---in-GStreamer-1.22.0#2-ximagesink-support

* probably not "high priority" but also only requires a small effort.


The regression was unnoticed since being added in october 2022 (or Jan 2023 when 1.22 was released)  because it doesn't break  x86_64.  It does break arm because random uninitialized junk  usually triggers an X11parsing error (at least on R Pi) when ximagesink states.   No idea why x86 is immune.

* why would ximagesink as opposed to xvimagesink get used?      

* the bug emerged when someone was trying to develop a device with a Pi CM4 board and a  small 480x800
monitor which didn't support XV  X11 extensions, using our Airplay server.

I tracked the bug down to when it first appeared

Probably a rare use case.




https://github.com/FDH2/UxPlay/issues/277

https://github.com/FDH2/UxPlay/issues/280

**Comment by lurch** [comment]
> It's not a terribly high priority fix in my book.

> Probably a rare use case.

In that case I'll close this issue.

**Comment by buhman** [comment]
I encountered this issue. I managed to compile gstreamer1.0-plugins-base by first learning how to compile a Debian source package. After that trivial patch, indeed ximagesink works.

I humbly suggest reconsidering backporting this.

**Comment by XECDesign** [comment]
> I humbly suggest reconsidering backporting this.

Is [this](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/6631/diffs) the patch you're talking about?

**Comment by buhman** [comment]
Yes, I think https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/6631/diffs is both trivial and highly valuable for me.

**Comment by XECDesign** [comment]
Merged the patch into the bookworm package yesterday. Is it okay now?
