### ISSUE TITLE
Boot options

### ISSUE THREAD

**Issue by gerryb** [raspberrypi/bookworm-feedback#271]
Now we have Pi 5 and NVMe booting we need the option to install a grub like multi boot menu. Image transfer to SSD needs control of partitions. Currently it takes over the lot. Gross amount for most projects.

Can  we have the ability to have multiple partitions on the SSD for different projects and backups  and at boot chose which one to run.

Apologies this is an idea, not a bud, but lack of this is buggy to me!

**Comment by lurch** [comment]
It sounds like you're looking for something like https://github.com/procount/pinn/ which indeed allows you to install multiple OSes and choose between them at boot time. But PINN is a 3rd-party project, and not directly supported by Raspberry Pi, so I'll close this issue.
