### ISSUE TITLE
ffplay is too slow to play HEVC 4K / 60FPS video files

### ISSUE THREAD

**Issue by qrp73** [raspberrypi/bookworm-feedback#273]
Steps to reproduce:
1) Open virtual virtual terminal: Alt+Ctrl+F1
2) ```wget https://img.photographyblog.com/reviews/apple_iphone_13_pro/sample_images/4K60p.mov```
3) ```ffplay 4K60p.mov```

Expected result: playback is no worse than with VLC player

Actual result: playback is very laggy and almost not watchable while the same file can be played with VLC player with watchable speed.

The same issue happens when running ```ffplay 4K60p.mov``` from Wayfire terminal window

Tested on RPI 4 rev 1.5
```
$ uname -a
Linux raspi 6.6.32-v8+ #1 SMP PREEMPT Fri Jun  7 16:39:58 UTC 2024 aarch64 GNU/Linux
```

**Comment by jc-kynesim** [comment]
ffplay is effectively only a demo program and doesn't have any display stages that can efficiently deal with hardware buffers. VLC does. So, sorry, this is never going to work.

**Comment by lurch** [comment]
Thanks for the info John!
