### ISSUE TITLE
Wrong Taskbar Labels

### ISSUE THREAD

**Issue by heliacer** [raspberrypi/bookworm-feedback#276]
When disconnecting from a Bluetooth device, It says `Installing Updates`

Here's a demonstration Image
![image](https://github.com/user-attachments/assets/bc673fd9-d465-496c-8b60-456454b3742c)

**Comment by lurch** [comment]
ping @spl237 - looks like this is picking up an incorrect window-title from somewhere.

**Comment by spl237** [comment]
Fixed for next release - many thanks.
