### ISSUE TITLE
Appearence settings won't open

### ISSUE THREAD

**Issue by deety19** [raspberrypi/bookworm-feedback#282]
PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)" installed  approx 14:00 26/7/24

Main menu  preferences/appearance settings   will not open.
Preferences/Screen Configuration/Layout/Screens   results in empty menu

**Comment by XECDesign** [comment]
Seems to be okay on my end. Any interesting output if you run 'pipanel' in a terminal window?

**Comment by PaulaT** [comment]
Just confirming issue!
Whilst headless and using Real-vnc-viewer, I get a notification of "Loading Configuration Settings - please wait" but no appearance of pipanel, trying via terminal, I get the same answer as bug #254 Vis:

(pipanel:2642): Gtk-CRITICAL **: 14:29:53.478: gtk_file_chooser_select_filename: assertion 'filename != NULL' failed
Segmentation fault

Trying using suggestion from sgalke on 22nd May, gives access via default low-resolution screen but pipanel will appear.
Testing with Rpi3 using default 20240704 bookworm 32bit image out of the box.
Hope this helps.

**Comment by luxdi** [comment]
Just adding to this. Did a clean install of Bookworm today. Using RealVNC Viewer, I get a notification of "Loading Configuration Settings - please wait" then nothing.

**Comment by XECDesign** [comment]
@spl237 Any idea what this might be about?

**Comment by spl237** [comment]
Fix uploaded to apt.

**Comment by luxdi** [comment]
Sorry for being a bit thick but how do we actually fix this issue with a running version of Bookworm? What does the "Fix uploaded to apt." mean?

**Comment by spl237** [comment]
Wait a few hours; then either do "sudo apt update" followed by "sudo apt full-upgrade" in a terminal window, or alternatively reboot your Pi and then click on the update icon (circle with an arrow in it) which appears on the taskbar.

**Comment by luxdi** [comment]
Thank you. I had tried that, but I was too soon. I'll try again later.

**Comment by luxdi** [comment]
OK, I've updated fine. Thing is none of the changes are sticking. E.g. changing the desktop wallpaper and clicking OK doesn't do anything; same for all the other settings except light/dark theme which seems to work.

**Comment by spl237** [comment]
Works fine for me here. Try going to the Defaults tab in Appearance Settings and choosing one of the options; that deletes any changes to appearance and starts again from clean. Sounds as if something is corrupt somewhere in your image, or you have somehow managed to make the appearance config files non-writable.

**Comment by PaulaT** [comment]
Confirmed fixed on either gui or command line after loading update.
pipanel/stable,now 1:1.48 armhf [installed,automatic]
Thanks Simon.
