### ISSUE TITLE
python3-buildhat isn't in the APT repo yet

### ISSUE THREAD

**Issue by lurch** [raspberrypi/bookworm-feedback#29]
I was told it would be added, so that's what I documented in https://github.com/raspberrypi/documentation/blob/bookworm/documentation/asciidoc/accessories/build-hat/py-installing-software.adoc :slightly_smiling_face:

**Comment by XECDesign** [comment]
Just checked apt and it seems to be there as python3-build-hat

**Comment by lurch** [comment]
Thanks, fixed in https://github.com/raspberrypi/documentation/pull/3131
