### ISSUE TITLE
error installing homeassitant: brcmfmac: brcmfmac_set_channel.. reason -52

### ISSUE THREAD

**Issue by frdsky** [raspberrypi/bookworm-feedback#290]
Trying to install Homeassistant to a fresh Raspberry Pi 4b us, us. Get multiple errors "brcmfmac: brcmfmac_set_channel.. reason -52", then install failed. 
Trying to move older Raspberry Pi 4b to an SSD also fails.
Homeassistant programmers says its a RPI kernel problem and we should create a file in /etc/modprobe.d/ "brcmfmac.conf", but the filesystem on the installation-disk does not allow writing. 
See also:
https://archlinuxarm.org/forum/viewtopic.php?t=17010&p=72799#p72819 
https://github.com/home-assistant/operating-system/issues/3367#issuecomment-2269028464

**Comment by ghollingworth** [comment]
It looks like HomeAssistant is incorrectly configured for PI 4 Wifi.  Unless you can reproduce this issue using a Raspberry Pi OS latest release with your AP, I think this is a problem with the configuration of the distribution.  Reopen if you can reproduce
