### ISSUE TITLE
labwc: mouse cursor selection slightly broken

### ISSUE THREAD

**Issue by andrum993** [raspberrypi/bookworm-feedback#291]
See https://forums.raspberrypi.com/viewtopic.php?t=370970 for full description.

The summary is that cursor handling on the default Raspberry Pi OS desktop currently has issues, but I've flagged this against labwc since it is more of an issue with labwc - see below.

(It is not possible to file an issue against Raspberry Pi's labwc repo, and I don't know if the fault actually lies in labwc, chromium-browser, or something else, so this repo seemed the most appropriate location for raising this. Also, the beta forum thread where this was originally raised has not been picked up - it was originally reported by 'botspot' in May 2024).

Problems:

1. Not all commonly-used cursor types (e.g. zoom-in and zoom-out) are defined in the default theme (PiXflat). This means that for those cursors, the app will fall back to the default pointer cursor. This is the case with the default Wayfire compositor.

2. With labwc selected as the compositor however, cursor handling is worse in the included chromium-browser (but not, it seems, other apps, including Firefox). In chromium-browser, there is no fallback to the default pointer cursor. Instead, when there is an unsupported cursor selected (e.g. zoom-out), the cursor vanishes.

The site https://nabeelgit.github.io/cursor-changer/ can be used as a handy test of browser cursor handling.

**Comment by spl237** [comment]
I've added symlinks for the missing cursors to our theme - if you update, you should at least find you have a cursor (in most cases the default) where they were missing before.
