### ISSUE TITLE
Wastebasket (trash) icon does not reappear on desktop after removing tick and later reticking it via " Appearance settings" 

### ISSUE THREAD

**Issue by MuppsGit** [raspberrypi/bookworm-feedback#292]
Wastebasket icon does not reappear on desktop after removing tick and later reticking it in "Appearance settings" --> Desktop --> Wastebasket,
This is on a Raspberry pi 5 with the latest version en updates.

On an old Pi4 this works fine.

**Comment by spl237** [comment]
I am fiddling with the desktop at the moment and did see a crash associated with changing the desktop items in Appearance Settings when I was testing yesterday, so I have seen something similar - will investigate.

**Comment by spl237** [comment]
Are you still using the default wayfire compositor, or have you used raspi-config to switch to labwc? (If this question makes no sense to you, then you are still using wayfire!) Many thanks.

**Comment by spl237** [comment]
OK, have just tried this with the latest image and all updates, in wayfire, labwc and X, and cannot repeat it. I suspect you may have a corrupted configuration file somewhere.

Try launching Appearance Settings, going to the Defaults tab and resetting to defaults - if that doesn't fix the problem, please reopen.

**Comment by MuppsGit** [comment]
Hi Simon. Excuses for the late answer and thank you for trying to replicate the issue and find the cause.
Still using wayfire. Ive tried going back to defaults in Appearance settings but still didnt work. Maybe as u say the config file is corrupted in some way. Will see if i can find it and otherwise do a fresh install. Thanks again.

**Comment by popcornmix** [comment]
A quick test here and it seems to work fine. Wastebasket disappears and appears with the checkbox.
