### ISSUE TITLE
"python3 /usr/share/system-config-printer/applet.py" process eats memory

### ISSUE THREAD

**Issue by qrp73** [raspberrypi/bookworm-feedback#293]
I found that there is process "python3 /usr/share/system-config-printer/applet.py" which running in background and eats about 16 MB memory. The content shows that this is something related to printer, but there is no printer and cups service is disabled. 

I tried to remove it with ```sudo apt remove system-config-printer``` and it disappears after reboot.

What is the reason for this process to run in background and to eat memory/CPU when there is no printers?

**Comment by ghollingworth** [comment]
It's a standard component for CUPS, https://github.com/OpenPrinting/system-config-printer

If you don't want printer support it's safe to remove the package
