### ISSUE TITLE
maxima segmentation violation error

### ISSUE THREAD

**Issue by foompah** [raspberrypi/bookworm-feedback#297]
Steps to reproduce:

sudo apt install maxima
Start maxima
Expected result: maxima is started and works

Actual result: Segmentation violation error

app log:
$ maxima
mprotect failure: 0xb29000 41320448 : Invalid argument

Unrecoverable error: Segmentation violation..
Aborted

**Comment by lurch** [comment]
This package comes directly from upstream Debian, so you should probably report it there? https://packages.debian.org/bookworm/maxima

**Comment by foompah** [comment]
RPiOS 32-bit doesn’t have this bug. Ubuntu 64-bit doesn't have this bug. The wxmaxima flatpak doesn't have this bug. This is all on a RPi 5 8GB.

From: Andrew Scheller ***@***.***>
Date: Tuesday, September 24, 2024 at 6:52 AM
To: raspberrypi/bookworm-feedback ***@***.***>
Cc: foompah ***@***.***>, Author ***@***.***>
Subject: Re: [raspberrypi/bookworm-feedback] maxima segmentation violation error (Issue #297)

This package comes directly from upstream Debian, so you should probably report it there? https://packages.debian.org/bookworm/maxima

**Comment by ghollingworth** [comment]
It's likely to be a 16kbyte page issue.

**Comment by popcornmix** [comment]
> It's likely to be a 16kbyte page issue.

If it runs with `kernel=kernel8.img` in config.txt, then that would confirm this theory.

**Comment by foompah** [comment]
Yes, with kernel=kernel8.img, it runs.

**Comment by martignoni** [comment]
> This package comes directly from upstream Debian, so you should probably report it there? https://packages.debian.org/bookworm/maxima

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1106352 (thanks to @sangwinc).
