### ISSUE TITLE
Issue setting WiFi country requires kernel patch

### ISSUE THREAD

**Issue by ghollingworth** [raspberrypi/bookworm-feedback#3]
https://forums.raspberrypi.com/viewtopic.php?t=354313&sid=6c7a670a1aea59e78eb573c8ed09a259#p2124616

**Comment by popcornmix** [comment]
Looks like that is in rpi-update kernel. 
We can bump stable kernel before bookworm release.
Perhaps wait for @pelwell to check if there's anything else we want to include in bump
(or any recent commits we are concerned about).
From my point of view, I'm not aware of any reason not to bump stable.

**Comment by pelwell** [comment]
Likewise - no reason not to update stable to the latest 6.1, it's been quiet for a while.

**Comment by lurch** [comment]
IIRC this kernel also includes the patch that improves the compatibility between the Touch Display and the Camera Module 3 ?

**Comment by XECDesign** [comment]
This was fixed a while back.

**Comment by martignoni** [comment]
Confirming. Fixed as image 2023-09-22:
```
$ sudo update-alternatives --display regulatory.db
regulatory.db - auto mode
  link best version is /lib/firmware/regulatory.db-debian
  link currently points to /lib/firmware/regulatory.db-debian
  link regulatory.db is /lib/firmware/regulatory.db
  slave regulatory.db.p7s is /lib/firmware/regulatory.db.p7s
/lib/firmware/regulatory.db-debian - priority 100
  slave regulatory.db.p7s: /lib/firmware/regulatory.db.p7s-debian
/lib/firmware/regulatory.db-upstream - priority 50
  slave regulatory.db.p7s: /lib/firmware/regulatory.db.p7s-upstream
```
