### ISSUE TITLE
Taskbar CPU Monitor

### ISSUE THREAD

**Issue by gestef** [raspberrypi/bookworm-feedback#304]
Hi, it seem the taskbar CPU monitor gadget have a problem in visualization, 
When it is enabled and the taskbar is not at the standard dimension (36 pixel) but for example at 70 pixel, will appear another cpu motor with diffrent color but same information in it.
![Cpu_monitor](https://github.com/user-attachments/assets/bfd7d8ff-269a-4c34-a37b-aa2ec6921070)
there is no reason for exist and cannot be removed...

**Comment by lurch** [comment]
How did you set the non-standard taskbar height like that?

**Comment by spl237** [comment]
Only happens in lxpanel, which is imminently going to be obsolete, so wontfix.

**Comment by gestef** [comment]
> How did you set the non-standard taskbar height like that?

I have not installed It, i have create Raspberry sdcard with last bookwarm and the traybar Is this, i update os every week, how can i change It?

**Comment by lurch** [comment]
We're hoping to release a new OS-image in a few weeks, so for now you'll just have to wait.
