### ISSUE TITLE
After changing to labwc lightdm login background vanished.

### ISSUE THREAD

**Issue by MattiJarvinen** [raspberrypi/bookworm-feedback#309]
Greeter background is just a solid color and not the same/similar image as /usr/share/rpd-wallpaper/RPiSystem.png it used to be.

Also I can't seem to find a way to configure a background.

**Comment by MattiJarvinen** [comment]
Ah, found it there was a recent change done to the pi-greeter that adding drop shadow, it removed the greeter background.

https://github.com/raspberrypi-ui/pi-greeter/commit/82cb5c4647bf427c4145380379e8e9debc991dfe

wallpaper= /usr/share/rpd-wallpaper/RPiSystem.png
wallpaper_mode=crop

It would be very nice if the /etc/lightdm/pi-greeter.conf would contain commented out configuration options with some explanations.

**Comment by spl237** [comment]
By design - the trick used to give a shadowed undecorated greeter window causes a spurious border on labwc; a plain background hides this.

**Comment by spl237** [comment]
Have now managed to fix this - update will be in apt today to restore greeter background image.
