### ISSUE TITLE
Labwc crashes. How to enable logging?

### ISSUE THREAD

**Issue by CrendKing** [raspberrypi/bookworm-feedback#317]
I switched from Wayfire to Labwc, and experiencing Labwc crashing when a program of mine which uses [enigo](https://github.com/enigo-rs/enigo/) to simulate keyboard inputs. This program works fine under Wayfire. It also has no problem for mouse inputs.

Before I report this to enigo, I'd like to enable debug logging of Labwc to a file, so I can give them more info. I tried to modify `/usr/bin/labwc-pi` with `exec /usr/bin/labwc -m $@ --debug > /tmp/labwc.log`, but then labwc will fail to start at all.

**Comment by spl237** [comment]
Try removing the $@ from that line.

**Comment by CrendKing** [comment]
Nothing changed. Just to be sure, this is the line I tried: `exec /usr/bin/labwc -m --debug > /tmp/labwc.log`

**Comment by CrendKing** [comment]
Thanks. I got the log at crash. Reported to [enigo](https://github.com/enigo-rs/enigo/issues/356)

**Comment by Consolatis** [comment]
Please also report the bug at https://github.com/labwc/labwc. Even if enigo is doing something wrong labwc should not crash because of it. The log you posted in the enigo issue does not contain the relevant part for labwc itself (might need a `2>&1` to also catch stderror).

**Comment by CrendKing** [comment]
That's all the log I can get. The command line was something like `labwc -m --debug 2>/tmp/labwc.log`. If I do `2>&1 >/tmp/labwc.log`, labwc would not even start (which I do not understand).
