### ISSUE TITLE
OverlayFS on root filesystem not working in RPI5 due to wrong initramfs image update

### ISSUE THREAD

**Issue by snask1** [raspberrypi/bookworm-feedback#326]
### System
RPI5 with up-to-date Bookworm lite installation.

### Steps to Reproduce
- Enable read-only file system and read-only boot partition in  `raspi-config`  > `4 Performance Options` > `P2 Overlay File System Enable/disable read-only file system` 
- Reboot

### Expected Results
-  Read-only mount for `/boot/firmaware` 
-  Overlay mount for root,  i.e. `overlayroot  on  /  type overlay (rw, ...`

### Actual Results
- `/boot/firmaware` is read-only
- ext4  mount for root: ` /dev/xxx  on / type ext4 (rw, ...`

### Root Cause
Setting prementioned configs in `raspi-config` triggers installation of `overlayroot` package which runs imitramfs update (postinstall) but it seems that only `rpi-v8` images are updated: (`/boot/initrd.img-6.6.51+rpt-rpi-v8` and `/boot/firmware/initramfs8`). The same files are update by  `update-initramfs -u`. However, some research revealed that RPI5 should run `-rpi-2712` -kernel which indeed seems to be the case:
``` 
$ uname -a
Linux td1 6.6.51+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 GNU/Linux
```
The problem can be resolved by updating correct image explicitly:
```
sudo update-initramfs -c -k $(uname -r)
``` 

### Sytem Details
```
$ cat /etc/rpi-issue && cat /etc/os-release
Raspberry Pi reference 2024-11-19
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 891df1e21ed2b6099a2e6a13e26c91dea44b34d4, stage2
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
...
```
```
$ apt policy initramfs-tools && apt policy overlayroot
initramfs-tools:
  Installed: 0.142+rpt1+deb12u1
  Candidate: 0.142+rpt1+deb12u1
  Version table:
 ...
overlayroot:
  Installed: 0.18.debian13+deb12u1
  Candidate: 0.18.debian13+deb12u1
  Version table:
 ...
```

**Comment by XECDesign** [comment]
I've updated initramfs-tools to update all of the initramfs files for all flavours of the latest kernel version. Hopefully now it behaves more like what I was intending.
