### ISSUE TITLE
ADS7846 in Raspberry Pi OS lite 6.6.62 (2024-11-25) no touch on RPI5

### ISSUE THREAD

**Issue by noobmaster777** [raspberrypi/bookworm-feedback#331]
Using Raspberry Pi 5, rpi os lite bookworm, I put a waveshare35a (or a 3.5 clone with xpt2046, i have 2) touchscreen. On my config.txt: dtoverlay=piscreen,rotate=180,drm. Screen works but touch is not detected.
Testing with the script found here, https://forums.raspberrypi.com/viewtopic.php?t=365189 I determined that my gpio 17 (interrupt pin) is ok. 
![IMG_1210](https://github.com/user-attachments/assets/d73b9aa4-2a6f-43ff-876b-90853b29179e)
For more info, my pi is booting from nvme and is connected to a MAX98357A but I have tried using an SD card as well with nothing connected and same results. Has anybody made the touch on a waveshare35a work with the latest images? Thanks

**Comment by noobmaster777** [comment]
my config.txt:
dtparam=i2c_arm=on
dtparam=spi=on
dtoverlay=max98357a
camera_auto_detect=1
#display_auto_detect=1
auto_initramfs=1
#dtoverlay=vc4-kms-v3d
#max_framebuffers=2
disable_fw_kms_setup=1
arm_64bit=1
disable_overscan=1
dtoverlay=piscreen,rotate=180,drm
dtparam=pciex1_gen3


Dmesg says this: Is this possibly related to the problem? 
![IMG_1215](https://github.com/user-attachments/assets/8c87057b-bb44-4c87-8a48-ba8b15da8537)

**Comment by lurch** [comment]
@6by9 Is `bookworm-feedback` the right place for this, or should it be transferred to the `linux` repo?

**Comment by 6by9** [comment]
It's a continuation of https://github.com/raspberrypi/bookworm-feedback/issues/88, which noobmaster777 tagged on the back end of.

It has reminded me of an issue not so long back where an interrupt line definition in an overlay missed out any pinctrl directives, and we ended up with the GPIO not actually connected to the pin. I'll try and refresh my memory on that one.

**Comment by noobmaster777** [comment]
Thanks @6by9 i hope its a software problem so I dont have to change hardware. Warm regards!

**Comment by 6by9** [comment]
I've just tested my [piscreen clone](https://www.amazon.co.uk/ELEGOO-480x320-Raspberry-Monitor-Interface/dp/B01MRQTMTD) on an 8GB Pi5

Other than needing to add the `frequency=18000000` override to slow the SPI down slightly, I needed no changes. (Actually it seems stable at the default on this Pi, but I have had variation)
As it's my main development system it happens to be on a 6.12 kernel, but I'm not expecting that to make any difference. Feel free to `sudo rpi-update rpi-6.12.y` to grab the test 6.12 kernel if you want to replicate.

**Comment by noobmaster777** [comment]
> I've just tested my [piscreen clone](https://www.amazon.co.uk/ELEGOO-480x320-Raspberry-Monitor-Interface/dp/B01MRQTMTD) on an 8GB Pi5
> 
> Other than needing to add the `frequency=18000000` override to slow the SPI down slightly, I needed no changes. (Actually it seems stable at the default on this Pi, but I have had variation) As it's my main development system it happens to be on a 6.12 kernel, but I'm not expecting that to make any difference. Feel free to `sudo rpi-update rpi-6.12.y` to grab the test 6.12 kernel if you want to replicate.

Just tested on 6.12 via update and sadly its still not working. Do you mean 'speed=18000000'? Are you using the piscreen overlay?

**Comment by noobmaster777** [comment]
After much investigation, I borrowed a friends 3.5 inch touch screen and discovered that both my screens are busted! Apologies for the hassle and thanks for the guidance. Closing this!
