### ISSUE TITLE
mount: (hint) your fstab has been modified, but systemd still uses the old version

### ISSUE THREAD

**Issue by reraikes** [raspberrypi/bookworm-feedback#34]
This issue is not corrected in image_2023-09-22-raspios-bookworm-arm64-lite.img:

*****
root@raspberrypi:~# mount /dev/sda3 /mnt
mount: (hint) your fstab has been modified, but systemd still uses
       the old version; use 'systemctl daemon-reload' to reload.
*****

/etc/fstab has not been altered since the last reboot:

root@raspberrypi:~# ls -l /etc/fstab
-rw-r--r-- 1 root root 364 Sep 21 22:58 /etc/fstab

Running 'systemctl daemon-reload' eliminates the message until the next reboot.

See: https://forums.raspberrypi.com/viewtopic.php?t=356461

**Comment by reraikes** [comment]
This issue is NOT corrected in the 2023-09-28 image.

**Comment by popcornmix** [comment]
Let this continue here: https://github.com/RPi-Distro/repo/issues/346
