### ISSUE TITLE
rc_gui: tooltip incorrectly mentions RealVNC

### ISSUE THREAD

**Issue by andrum993** [raspberrypi/bookworm-feedback#35]
Just spotted a bug in `rc_gui` (the GUI-based Raspberry Pi Configuration tool). On the `Interfaces` tab, if you hover over the `VNC:` switch it shows a tooltip which says `Turn on to enable remote access using RealVNC`. This is on a Pi 4B running Wayland, so it won't be using RealVNC. Probably `RealVNC` should be replaced with `VNC` to make it generic.

**Comment by andrum993** [comment]
This has now been corrected in the English-language version of the rc_gui UI: https://github.com/raspberrypi-ui/rc_gui/commit/ba4354cf99c8e190c5641630c4909311ff95cc5a

Translations have not been updated yet, and the `msgid` should probably be changed when they are, to avoid any confusion.

**Comment by lurch** [comment]
Fixed, but not yet pushed.
