### ISSUE TITLE
raspbian-archive-keyring should not have any dependencies

### ISSUE THREAD

**Issue by outis151** [raspberrypi/bookworm-feedback#36]
`raspbian-archive-keyring` currently depends on `gnupg` which unnecessarily adds a dependency on the entire gnupg suite.
The required package for `apt` signature verification (`gpgv`) is already a dependency of `apt` itself.

Upstream debian do not add a dependency on `gnupg` on their keyring package either (https://packages.debian.org/bookworm/debian-archive-keyring).

Moreover, apt also has a dependency on `raspbian-archive-keyring` which is also not required (and not done by upstream debian either)

```
raspbian-archive-keyring
  Depends: gnupg
```

**Comment by XECDesign** [comment]
That's not our package. It comes from Raspbian.

**Comment by outis151** [comment]
Thank you for the clarification, closing the issue
