### ISSUE TITLE
Webcam support on chromium?

### ISSUE THREAD

**Issue by steveiliop56** [raspberrypi/bookworm-feedback#46]
Camera works fine in Firefox but what about chromium?

**Comment by ghollingworth** [comment]
libcamera is never likely to work in Chromium.

**Comment by 6by9** [comment]
Chromium hasn't added support for Pipewire which is the the preferred way for patching in libcamera. Patches have been floating around for a while, but Google generally do their own thing.

**Comment by steveiliop56** [comment]
So we may see Firefox coming as the default browser?

**Comment by lurch** [comment]
If you look in the "Raspberry Pi Configuration" program, you'll see that there's an option to set Firefox (or Chromium) as your default browser.
