### ISSUE TITLE
Update-notification in systray ignores CLI updates

### ISSUE THREAD

**Issue by lurch** [raspberrypi/bookworm-feedback#48]
I wrote the 10th Oct Bookworm image onto an SD card, and during the first-boot wizard I skipped the option to install updates. When I get to the desktop, I get the update-icon in the top-right corner, but out of habit I did `sudo apt full-upgrade` in a Terminal window instead, and the update-notification stayed in the systray.
I wondered if it might "auto clear" after a while (e.g. perhaps it does a periodic check to see if there are any updates available?), but after leaving the desktop idle for over an hour, the update-icon is still there.

**Comment by ghollingworth** [comment]
It only checks once a day.  So works as expected.
