### ISSUE TITLE
What instructions does Bookworm have to control the latest Pi5-PCIe interface?

### ISSUE THREAD

**Issue by Tiger0215** [raspberrypi/bookworm-feedback#54]
What instructions does Bookworm have to control the latest Pi5-PCIe interface?
Is there a corresponding PCIe interface pin definition diagram?

**Comment by aallan** [comment]
This isn't really a Bookworm question, it's a Raspberry Pi 5 question. Documentation around the Raspberry Pi connector for PCIe and the FPC cable, along with a discussion of how to enable PCIe, will be published at or around the time when hardware ships to the public later this month.

**Comment by Tiger0215** [comment]
Thank you for your reminder and correction.
