### ISSUE TITLE
vnc Server : Tigervnc is only able to connect if my only user (pi) is logged into the pi desktop directly on the pi

### ISSUE THREAD

**Issue by PitHerm** [raspberrypi/bookworm-feedback#55]
Pi 4 B Bookworm 32 bit

it works fine (ok slow but fine) while the local user stays logged in.
if i hit logout on Pi desktop within tigervnc the local user is logged out too.
after that no connection can be stablished until the local user is logged in again.

**Comment by popcornmix** [comment]
Duplicate of https://github.com/raspberrypi/bookworm-feedback/issues/42
