### ISSUE TITLE
window title disappearing issue

### ISSUE THREAD

**Issue by qrp73** [raspberrypi/bookworm-feedback#58]
Steps to reproduce:

1) install mesa-utils:
```
sudo apt install mesa-utils
```
2) run glxgears from console
3) click on window with gears to get focus on it and press Ctrl+Alt+CursorLeft and then Ctrl+Alt+CursorRight

Expected result: window dock on left display side and then on right display side, window title is present

Actual result: window dock works ok, but window title disappears after dock to the right display side - BUG

Note: the same issue with window title disappearing happens with any app window and in different scenarios. I just wrote steps to reproduce for most easy and stable reproducible way to catch it. Most of the time it happens with maximized windows.

Note2: I found that this bug easy to reproduce on window which has OpenGL rendering. But it also happens in lxterminal, geany editor and other apps.

**Comment by popcornmix** [comment]
I can reproduce.

**Comment by spl237** [comment]
Fixed - when switching between two tiled configurations, the titlebar was mistakenly being cleared. Will be in next update.

**Comment by qrp73** [comment]
yes, it is fixed after last update. Thanks
