### ISSUE TITLE
Update vscode package to v1.81.1

### ISSUE THREAD

**Issue by paulober** [raspberrypi/bookworm-feedback#7]
The vscode package `code` was not updated in the bookworm repositories and is still the vscode February 2023 update also delivered in the bullseye repositories (v1.76.0).

Since then there have been some important changes especially to the extensions runtime. Would be nice if we could get the most recent release of vscode with bookworm.

**Comment by theofficialgman** [comment]
alternative idea. take releasing bookworm as an opportunity to restore control back to microsoft and have their apt repos handle vscode distribution like on all other platforms. this could be a simple toggle in initial setup whether the user wants vscode (with the microsoft repo that comes with it) included or not.

**Comment by XECDesign** [comment]
Previously, the packages list contained the latest version as the first entry, which no longer seems to be the case.

Added a fix to our update script which sorts the versions to determine what the latest is.

Should be resolved in bullseye now and should be fixed in bookworm in a little bit.

**Comment by paulober** [comment]
@XECDesign Perfect. Thanks for the quick fix. It's already updated on bullseye and bookworm.
