### ISSUE TITLE
Outdated boot.tar.xz and root.tar.xz

### ISSUE THREAD

**Issue by solskogen** [raspberrypi/bookworm-feedback#78]
The boot.tar.xz and root.tar.xz files in https://downloads.raspberrypi.org/raspios_* are not bookworm files. They were last updated in 2022.

**Comment by XECDesign** [comment]
What are you using them for? Those were used by NOOBS, which has been deprecated for quite a while.

**Comment by solskogen** [comment]
In that case, they should be removed :-)

**Comment by XECDesign** [comment]
While bullseye is the ‘legacy’ release, I don’t think that’s a good idea.
