### ISSUE TITLE
In rc_gui, the Interfaces-->VNC switch is disabled

### ISSUE THREAD

**Issue by JinShil** [raspberrypi/bookworm-feedback#79]
It appears rc_gui is checking if realvnc-vnc-server is installed instead of wayvnc.  Therefore, it's not possible to enable VNC through the GUI.  Enabling through raspi-config seems to work fine though.

https://github.com/raspberrypi-ui/rc_gui/blob/ba4354cf99c8e190c5641630c4909311ff95cc5a/src/rc_gui.c#L117

**Comment by spl237** [comment]
realvnc-vnc-server is always installed, so this should not be an issue.

**Comment by JinShil** [comment]
RealVNC cannot be used for for commercial purposes.  Therefore, in our OS, which is generated using pi-gen, real-vnc-server is not installed.

wayvnc can be used for commercial purposes, so in our OS it can be installed.  

rc_gui should probably check for real-vnc-server OR wayvnc.

**Comment by spl237** [comment]
Fixed - will be in next release.

**Comment by lurch** [comment]
> in our OS

This repo is for tracking issues with Raspberry Pi OS Bookworm, not third-party OSes. Bugs with `rc_gui` should probably be reported at https://github.com/raspberrypi-ui/rc_gui
