### ISSUE TITLE
 linux-version list - does not list anything 

### ISSUE THREAD

**Issue by CarlFK** [raspberrypi/bookworm-feedback#8]
$ linux-version list
(nothing)

I reported this here:
https://github.com/RPi-Distro/repo/issues/320

linux-version list
expects to find the version in the kernel file name.  

image_2023-07-28-raspios-bookworm-arm64-lite.img.xz
boot/kernel8.img

so re-opening this bug here in hopes that either the kernel filename get changed, 
or the patch to linux-version gets used.

**Comment by XECDesign** [comment]
Should be resolved

**Comment by martignoni** [comment]
It is indeed (image 2023-09-22):
```
$ linux-version list
6.1.0-rpi2-rpi-v8
```
