### ISSUE TITLE
Connect iPad as pi screen with touch functionality 

### ISSUE THREAD

**Issue by undeadskeleton** [raspberrypi/bookworm-feedback#81]
Using ssh to connect to my raspberry pi 400 but how to keep my iPad touch functionality and use it as screen for pi wirelessly

**Comment by undeadskeleton** [comment]
any kind of help will be appreciated

**Comment by popcornmix** [comment]
This repo is for reporting bugs in bookworm. This isn't the right place for this question.
For general support questions please use the [forum](https://forums.raspberrypi.com).
