### ISSUE TITLE
Clipboard issues

### ISSUE THREAD

**Issue by qrp73** [raspberrypi/bookworm-feedback#86]
Steps to reproduce:
1) Start Text Editor (mousepad)
2) type 12345
3) select text 234
4) Press Ctrl+Instert to copy text into clipboard
5) Close Text Editor
6) Start new Text Editor
7) Press Shift+Insert to paste previously copied text.

Expected result: text "234" is inserted

Actual result: nothing happens - BUG

8) Right click on Text Editor to get context menu
9) Select menu item Paste

Expected result: text "234" is inserted

Actual result: nothing happens - BUG

10) Right click on Text Editor to get context menu
11) Select menu item Paste Special->Paste from History

Expected result: text "234" should be proposed to insert

Actual result: "No clipboard data" popuip appears - BUG

**Comment by spl237** [comment]
Clipboard handling in Wayland is limited, again due to the security model. The contents of the clipboard are only retained for as long as the application from which they are copied remains running. So in this case, because you are closing the text editor and then re-opening it, the previously copied text is lost when the application is closed.

This is just the way Wayland works and is not fixable.

**Comment by popcornmix** [comment]
It appears there exist clipboard managers, some may support wayland.
I've not worked out which would be the most suitable, but google will find information.

This may be a starting point: https://wiki.archlinux.org/title/clipboard

> It is also important to realize that according to the selection protocols, nothing is copied [until it is pasted](https://unix.stackexchange.com/questions/213840/how-to-toggle-or-turn-off-text-selection-being-sent-to-the-clipboard/213843#213843). For example, if you select some word in a terminal window, close the terminal and then want to paste it somewhere else, it will not work because the terminal is gone and the text has not been copied anywhere. If you want the word to be preserved after closing terminal window, consider installing a [clipboard manager](https://wiki.archlinux.org/title/Clipboard_manager).

**Comment by qrp73** [comment]
But there is also another issues. For example Shift+Insert may insert garbage text sometimes with proper text length but invalid content (catch it a lot of times in lxterminal) or just do nothing, but if I do paste through context menu with mouse it works ok. I still didn't catch a way to reproduce it, because this is floating bug (probably depends on some conditions), so this bug is not included in this issue, but I wanted to add it later...

**Comment by qrp73** [comment]
After all, I found how to fix it. 
Just install clipman and configure wayfire to use it:

```sudo apt install clipman```

then ```nano ~/.config/wayfire.ini```
```
[autostart]
clipman-restore = clipman restore
clipman-store = wl-paste -t text --watch clipman store
```

Works great. Just wonder why it missing from clean install?
