### ISSUE TITLE
Bookworm lifting USB current limit doesn't seem to work?

### ISSUE THREAD

**Issue by Tiger0215** [raspberrypi/bookworm-feedback#87]
When using the PD power supply, the USB port output current still does not reach 1.6A. Is there any instruction to test the USB output current or release the USB current limit?
I've currently used PD power, and lifted the USB current limit, but it doesn't work:
![I_VJ6C5GSK2E6X `W$8MCX5](https://github.com/raspberrypi/bookworm-feedback/assets/147788344/49311714-bc80-4d7b-ab60-f54df5764b66)

**Comment by ghollingworth** [comment]
Can you confirm:

* I'm assuming this is Pi 5?
* This is the official Raspberry Pi PD power supply?
* What does "vcgencmd get_config usb_max_current_enable" give
* What does the first boot screen say about the power supply (remove any booting media if you want to hang around on this screen for longer)

![image](https://github.com/raspberrypi/bookworm-feedback/assets/2048540/42f966a9-e020-4c39-8500-89312a96c589)

**Comment by Tiger0215** [comment]
`pi@raspberrypi:~ $ vcgencmd get_config usb_max_current_enable
usb_max_current_enable=1
`
But when I use a 1A electronic load on the USB interface, the USB interface power supply will continue to restart, that is, the measured USB output capability remains at 600mA.

**Comment by ghollingworth** [comment]
For completeness, can you answer the other questions?

**Comment by Tiger0215** [comment]
* I'm assuming this is Pi 5? --Y
* This is the official Raspberry Pi PD power supply? --N
* What does "vcgencmd get_config usb_max_current_enable" give -- "usb_max_current_enable=1"
* What does the first boot screen say about the power supply (remove any booting media if you want to hang around on this screen for longer) -- ""USB-PD 5000 mA""

**Comment by ghollingworth** [comment]
What do you get with:

pinctrl 49

**Comment by Tiger0215** [comment]
`pi@raspberrypi:~ $ pinctrl 49

49: op dh pd | lo // EN_MAX_USB_CUR/GPIO49 = output
`

**Comment by Tiger0215** [comment]
`49: op dh pd | lo // EN_MAX_USB_CUR/GPIO49 = output`

**Comment by Tiger0215** [comment]
When I connect an electronic load greater than 1A, the USB interface keeps restarting
I'm not sure if there is a command to monitor the output status of the USB interface. If there is, I can try to read it.

**Comment by timg236** [comment]
> `49: op dh pd | lo // EN_MAX_USB_CUR/GPIO49 = output`

That looks correct.

pin43 will tell you whether USB OC is asserted

**Comment by ghollingworth** [comment]
@timg236 @pelwell 

I've just tried adding:

```usb_max_current_enable=0```

in config.txt, I've confirmed with vcgencmd that

```
gordon@gordon@~$ vcgencmd get_config usb_max_current_enable
usb_max_current_enable=0
gordon@gordon@~$ pinctrl 49
49: op dl pd | lo // EN_MAX_USB_CUR/GPIO49 = output
```
Without the config.txt parameter, I get:

```
49: op dh pd | lo // EN_MAX_USB_CUR.GPIO49 = output
```

Is there something wrong with this output?  In this case it is driving high (dh), but reading back 'lo'

Gordon

**Comment by pelwell** [comment]
Yes, there's something wrong, as if the firmware isn't properly configuring the output (which is more complicated with RP1).

If you run `pinctrl 49 dh; pinctrl 49` you'll see no change. Ditto for `pinctrl 49 dl; pinctrl 49 dh; pinctrl 49`. But if you explicitly (re)set it to be an output it should spring into life:
```
pi@raspberrypi:~$ pinctrl 49
49: op dh pd | lo // EN_MAX_USB_CUR/GPIO49 = output
pi@raspberrypi:~$ pinctrl 49 op dh; pinctrl 49
49: op dh pd | hi // EN_MAX_USB_CUR/GPIO49 = output
```
So there are three things to do:
1. Find out what the firmware isn't doing and fix it (I'm looking at the RP1 GPIO support anyway).
2. Improve pinctrl so it can spot the problem and report it in some way.
3. Add a read-back option to pinctrl so you don't have to run it twice to make a change and observe the effect.

**Comment by Tiger0215** [comment]
`49: op dh pd | hi // EN_MAX_USB_CUR/GPIO49 = output
`
Yes, I can see that the IO port is in a high level state.
But unfortunately, the actual USB output capability remains unchanged.

**Comment by pelwell** [comment]
OK - I think the pinctrl output is red herring. The read value is wrong, but that's because the input enable has not been set on the pin. Running `sudo busybox devmem 0x1f000f8040 32 0x56` changes that, after which pinctrl shows that the pin level is high, as expected.

I can either display `--` for the level, or force the input enables to always be high - I think the former is safer and more informative.

**Comment by pelwell** [comment]
FYI, `pinctrl` has been updated with the change described above: https://github.com/raspberrypi/utils/commit/4f4c1744591a909bbc389428e64ba999f6d2f2c8
```
pi@raspberrypi:~$ pinctrl 49
49: op dl pd | -- // EN_MAX_USB_CUR/GPIO49 = output
```

**Comment by timg236** [comment]
@Tiger0215 Please could you post a photo of the underside of the board? High res around the RP1 area would be good to rule out some things
