### ISSUE TITLE
Netflix (and probably others) do not run in FireFox, but do in Chromium

### ISSUE THREAD

**Issue by GeekyTim** [raspberrypi/bookworm-feedback#9]
Netflix works fine in Chromium, but in FireFox ESR it reports Error Code: F7701-1003 (asking for FF to be upgraded).

**Comment by cillian64** [comment]
Could you try with the non-ESR Firefox stable (`117.0.1-1+rpt2` is the latest available)?  The ESR is pretty old and we haven't added Widevine support to it so I wouldn't expect netflix to work.
