### ISSUE TITLE
RasPiOS Lite images lack python3.11-venv needed to create Python virtual environment

### ISSUE THREAD

**Issue by DeeJay** [raspberrypi/bookworm-feedback#90]
With an as-installed unmodified Lite image of RasPiOS Bookworm from _2023-10-10-raspios-bookworm-arm64-lite_ or _2023-10-10-raspios-bookworm-armhf-lite_ the package **python3.11-venv** is not pre-installed.

This means it is not immediately/trivially possible to create a Python virtual environment.

```
david@rp0bw101032ltsd:~ $ python3 -m venv venvhack
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.11-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: /home/david/venvhack/bin/python3

david@rp0bw101032ltsd:~ $ 
```

Can be fixed by the end-user by installing that required package -
`sudo apt install python3.11-venv`

Installation by default seems preferable given the new situation calling for near-mandatory use of venvs by python users. Ref: #4

**Comment by popcornmix** [comment]
That seems reaonable. @XECDesign ?

**Comment by lurch** [comment]
https://github.com/RPi-Distro/pi-gen/blob/master/export-noobs/00-release/files/release_notes.txt#L109 says that this was fixed on 2023-12-05
