### ISSUE TITLE
oops, sorry

### ISSUE THREAD

**Issue by beta-tester** [raspberrypi/bookworm-feedback#92]
hi,
iinstalled 2023-10-10-raspios-bookworm-arm64.img.xz to an RPi 3B+, run throught the welcome and let it untouched for a long time. after comping back there was no HDMI signal anymore and did not come back after moving the mouse nor pressing any key.

i was able to ping the RPi from another computer.

so i thing the screen saver / screen blankingturned off the HDMI signal. but it does not reactivate HDMI when there is activity on mouse or keyboard.

**Comment by beta-tester** [comment]
oops, sorry. somebody took off the HDMI cable from TV.

**Comment by pelwell** [comment]
Thanks for the laugh!
