### ISSUE TITLE
Netboot doesn't like the suggested vers/proto options in official docs

### ISSUE THREAD

**Issue by trejan** [raspberrypi/bookworm-feedback#93]
This was tested on a Pi 5. I followed the [official guide for netboot](https://www.raspberrypi.com/documentation/computers/remote-access.html#set-up-nfs-root).

The new initramfs setup uses the userland [klibc nfsmount](https://git.kernel.org/pub/scm/libs/klibc/klibc.git) to mount the root FS. The issue is that nfsmount handles options differently than the kernel. nfsmount doesn't like the "vers=" option in cmdline.txt as it is [hardcoded to only accept 2 or 3](https://git.kernel.org/pub/scm/libs/klibc/klibc.git/tree/usr/kinit/nfsmount/main.c#n135) and doesn't recognise the "proto=" option. Having either of those two in cmdline.txt will cause boot to fail with an error message from nfsmount being repeatedly displayed.

Removing proto= and setting vers=3 in cmdline.txt will work but this downgrades to NFSv3. It appears to default to tcp anyway.

**Comment by reraikes** [comment]
I can confirm tejan's findings using a Raspberry Pi 3B+ as a server and a Raspberry Pi 4B as a client:

https://forums.raspberrypi.com/viewtopic.php?t=357877

**Comment by XECDesign** [comment]
Probably an issue for https://github.com/raspberrypi/documentation/?

**Comment by trejan** [comment]
Sure. Can you move this issue over? If not, I can make a new one over there.

**Comment by XECDesign** [comment]
I don't have those powers, but I'm sure someone does.

**Comment by trejan** [comment]
I've created https://github.com/raspberrypi/documentation/issues/3205
