### ISSUE TITLE
Broken window move leads to out of screen VLC window

### ISSUE THREAD

**Issue by qrp73** [raspberrypi/bookworm-feedback#99]
Steps To Reproduce:

1) Use display with resolution 1280x1024 (just for reference, can be reproduced with different resolution)
2) Open VLC player
3) resize window to about 320x200 and move window to the center of screen
4) Click File->Open and open file with 1920x1080 or 3840x2160 resolution 

Expected result: window is resized to fit within display resolution and window position is changed to keep window within display bounds 

Actual result: window is resized, but window position is not changed, so the large part of window appears out of screen

**Comment by qrp73** [comment]
Probably this issue happens because XMoveWindow function in XWayland is broken and needs to implement custom protocol for move window.

See mistakenly closed (not fixed) issue #56

**Comment by spl237** [comment]
As has been explained on that issue, the positioning of windows is not a bug and is not fixable; it is simply not possible under Wayland other than by the use of the layer-shell protocol, which is at the discretion of the application author. If an application has not been written to use layer-shell, it will be positioned according to the window manager, and anything done by the application to move itself will be ignored.

The issue has not been "mistakenly closed" - it is not an issue which can be fixed.
